"""
keylayout_to_xkb/emit/compose.py

Emit a self-contained XCompose file for a layout's dead-key compositions.

XKB symbols give the dead keys (dead_grave, dead_circumflex, ...) but NOT what
they compose to; that lives here. Each dead-key state becomes a set of XCompose
sequences:

    <dead_grave> <a>    : "ą"

i.e. the dead-key keysym, then the base character's keysym, producing the
composed result. The result is a quoted STRING, so multi-codepoint results
(combining-mark output with no precomposed form) are expressible here -- the
reason compositions go to XCompose rather than XKB single keysyms.

Self-contained on purpose: the emitted file does NOT `include "%L"` the host
locale's Compose, so the layout's behaviour does not depend on which Compose the
host happens to have. (A caller may add an include if they want host sequences
too, but the faithful macOS reproduction is exactly these sequences.)

Grounded on the installed XCompose syntax:
    <dead_X> <base> : "result"  keysym_name # COMMENT
The trailing keysym_name/comment are informational; the quoted result is what
the input method uses. We emit the quoted result plus a comment for readability.

Base keys are named by their XKB keysym via emit/classify.py. A base character
with no single keysym (rare for composition bases) is skipped with a warning
rather than emitted wrong, so a bad base never silently corrupts the file.
"""

from keylayout_to_xkb.common.models import Layout
from keylayout_to_xkb.common.debug import warn
from keylayout_to_xkb.emit.classify import (
    char_to_keysym,
    dead_state_keysym,
    reserve_placeholders,
)


__version__ = '20260623'


def _escape_result(text: str) -> str:
    """Escape a result string for an XCompose double-quoted literal.

    Backslash and double-quote must be escaped; everything else (including
    multi-byte UTF-8 and multi-codepoint sequences) passes through literally,
    matching how the system Compose file quotes results.
    """

    return text.replace('\\', '\\\\').replace('"', '\\"')


def _codepoint_comment(text: str) -> str:
    """A short 'U+XXXX' comment describing the result, for human readers."""

    points = ' '.join('U+{:04X}'.format(ord(ch)) for ch in text)
    return points


def emit_compose(layout: Layout, header_note: str = '') -> str:
    """Emit a self-contained XCompose file body for a layout's dead keys.

    Returns the file text. Iterates every dead state, names it via its dead_*
    keysym, and emits one sequence per composition. States whose accent maps to
    no dead_* keysym are skipped with a warning (the symbols emitter would also
    have skipped placing that dead key, so there is nothing to compose against).
    """

    lines = []
    lines.append('# XCompose for %s' % (layout.name or 'layout'))
    if header_note:
        lines.append('# %s' % header_note)
    lines.append('# Self-contained: does not include the host locale Compose.')
    lines.append('# Generated by keylayout_to_xkb. Not affiliated with Apple.')
    lines.append('')

    placeholders = reserve_placeholders(layout)

    total = 0
    for state_name, dead_state in sorted(layout.dead_states.items()):
        dead_keysym = dead_state_keysym(dead_state.terminator, dead_state.compositions)
        if dead_keysym is not None:
            trigger = dead_keysym
            header = '# %s  (terminator %r)' % (dead_keysym, dead_state.terminator)
        else:
            # No standard dead_* keysym for this accent (e.g. a numero sign, or a
            # Vietnamese base-vowel tone key). Use the dead-state PUA placeholder
            # the symbols emitter placed on the level, and document what it is so
            # the file stays comprehensible despite the opaque codepoint.
            trigger = placeholders['deadkey'].get(state_name)
            if trigger is None:
                warn('compose',
                     f'dead state {state_name!r} has neither a dead_* keysym nor '
                     f'a placeholder; skipping (this should not happen)')
                continue
            header = ('# %s  PUA placeholder dead key for terminator %r '
                      '(no standard dead_* keysym exists for it)'
                      % (trigger, dead_state.terminator))

        lines.append(header)

        # The bare placeholder alone produces the terminator (the accent/letter
        # the dead key emits when followed by a non-composing key). Named dead
        # keys get this from the host Compose; placeholder dead keys need it
        # stated explicitly so the bare press is not lost.
        if dead_keysym is None and dead_state.terminator:
            escaped_term = _escape_result(dead_state.terminator)
            lines.append('<%s>\t: "%s"\t# %s'
                         % (trigger, escaped_term,
                            _codepoint_comment(dead_state.terminator)))
            total += 1

        for base_char, result in sorted(dead_state.compositions.items()):
            if not base_char:
                continue

            base_keysym = char_to_keysym(base_char)
            if base_keysym is None:
                warn('compose',
                     f'composition base {base_char!r} in state {state_name!r} '
                     f'has no single keysym; skipping that entry')
                continue

            escaped = _escape_result(result)
            comment = _codepoint_comment(result)
            lines.append('<%s> <%s>\t: "%s"\t# %s'
                         % (trigger, base_keysym, escaped, comment))
            total += 1

        lines.append('')

    # Multi-character DIRECT key outputs: a single keypress that emits a multi-
    # codepoint string with no precomposed form (e.g. a Tibetan stacked vowel,
    # a Manipuri conjunct, a Vietnamese space+combining-mark). The symbols layer
    # places a PUA placeholder keysym on the level; here we emit the one-token
    # XCompose rule that expands that placeholder to the real string. This is the
    # same mechanism the X.Org Khmer Compose uses (<U17ff> : "string"). The
    # placeholder map is the SAME one the symbols emitter consumed, so the two
    # stay in lockstep.
    multichar = placeholders['multichar']
    if multichar:
        lines.append('# Multi-character key outputs (placeholder expansions)')
        for text, placeholder_keysym in sorted(
            multichar.items(), key=lambda item: item[1]
        ):
            escaped = _escape_result(text)
            comment = _codepoint_comment(text)
            lines.append('<%s>\t: "%s"\t# %s'
                         % (placeholder_keysym, escaped, comment))
            total += 1
        lines.append('')

    lines.insert(4, '# %d composition sequences' % total)
    return '\n'.join(lines)


# End of file #
