#!/usr/bin/env python3
"""
Self-contained installer for Apple macOS keyboard layouts converted to XKB.

Generated by keylayout_to_xkb. Not affiliated with or endorsed by Apple.

Installs the embedded layout(s) into the system XKB tree (/usr/share/X11/xkb,
recommended: visible to KDE's settings and previews) or your per-user tree
(~/.config/xkb, rootless; libxkbcommon >= 0.10.0). After installing, LOG OUT
and back in so the compositor rebuilds its keymap and the layout appears in
your keyboard settings picker.

Usage:
  python3 THIS_FILE.py                 interactive menu
  python3 THIS_FILE.py --list          list embedded layouts
  python3 THIS_FILE.py --install ID    install one layout by identifier
  python3 THIS_FILE.py --install-lang L install all layouts in a language group
  python3 THIS_FILE.py --install-all   install every embedded layout (user)
  python3 THIS_FILE.py --install-all-system  install every layout, symbols in
                                       the system location (keyboard preview
                                       works; uses sudo/doas/run0 as needed)
  python3 THIS_FILE.py --dump DIR      write the raw XKB/Compose files to DIR
  python3 THIS_FILE.py --force ...     rewrite even if unchanged
  python3 THIS_FILE.py --preview ID    print a layout's structured summary
"""

import os
import re
import sys
import json
import zlib
import pydoc
import base64
import shutil
import hashlib
import tempfile
import subprocess

from xml.sax.saxutils import escape as _xml_escape





_NAMESPACE = 'keylayout_to_xkb'
_BEGIN = '// >>> keylayout_to_xkb managed region (do not edit by hand) >>>'
_END = '// <<< keylayout_to_xkb managed region <<<'


def user_xkb_root():
    base = os.environ.get('XDG_CONFIG_HOME') or os.path.join(
        os.path.expanduser('~'), '.config')
    return os.path.join(base, 'xkb')


class InstallPaths:
    def __init__(self, root=None):
        self.root = root or user_xkb_root()
        self.symbols_dir = os.path.join(self.root, 'symbols')
        self.types_dir = os.path.join(self.root, 'types')
        self.rules_dir = os.path.join(self.root, 'rules')
        # Symbols now live in one file PER BASE LAYOUT, named '<base>x' (e.g.
        # 'plx', matching k2x_base_name), so the compositor finds our variant
        # sections inside a file named after the registered layout -- while NOT
        # shadowing the real system base (a user 'symbols/pl' would replace the
        # system Polish layout; 'symbols/plx' is a distinct file that shadows
        # nothing). The set of these files is dynamic, so symbols_file is gone;
        # use symbols_file_for().
        self.types_file = os.path.join(self.types_dir, _NAMESPACE)
        self.rules_file = os.path.join(self.rules_dir, 'evdev')
        self.registry_file = os.path.join(self.rules_dir, 'evdev.xml')
        self.compose_file = os.path.join(self.root, 'Compose.%s' % _NAMESPACE)
        self.manifest_file = os.path.join(self.root, '%s.manifest.json' % _NAMESPACE)

    def symbols_file_for(self, base_layout):
        """Path to the per-base symbols file for a base layout ('pl' -> the file
        symbols/plx)."""

        return os.path.join(self.symbols_dir, k2x_base_name(base_layout))


def k2x_base_name(base_layout):
    """The namespaced base-layout name we register under: 'pl' -> 'plx'.

    A distinct file/layout name so our variant sections are findable by KDE's
    preview (which looks in symbols/<layout>) without shadowing the real system
    base layout of the same language.

    The tag is a SINGLE trailing character ('x'), not '-k2x': KDE truncates the
    stored layout identity to a few characters (observed: 'pl-k2x' clipped to
    'pl-' in kxkbrc DisplayNames), and a truncated name no longer matches our
    rules -- so the compositor cannot resolve our types component and every key
    collapses to level 1 (Shift/AltGr/CapsLock stop working). 'plx' is short
    enough to survive the clip while staying distinct from the system 'pl'.
    Three-letter language codes ('ara') make FOUR-letter names ('arax');
    that is inside proven territory, since the truncation victim was the
    DASH form and the system itself ships the five-letter 'latam' working
    everywhere in KDE.
    """

    return '%sx' % (base_layout or 'us')


def _read(path):
    try:
        with open(path, 'r', encoding='utf-8') as handle:
            return handle.read()
    except FileNotFoundError:
        return None


def _write_if_changed(path, content, force):
    existing = _read(path)
    if existing is not None and existing == content and not force:
        return 'unchanged'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(content)
    return 'written'


def _split_variant_block(block_text):
    """Split an emitted variant block into (types_section, symbols_section).

    The emitter now produces ONLY an 'xkb_symbols "v" {...}' block -- every key
    references a STANDARD system type, so there is no custom xkb_types section to
    carry. types_section is therefore empty. (Retained as a tuple for callers that
    still distinguish the two components; the types file is written empty.)
    """

    symbols_index = block_text.index('xkb_symbols')
    types_part = block_text[:symbols_index].strip()
    if not types_part.startswith('xkb_types'):
        types_part = ''
    return (types_part, block_text[symbols_index:].rstrip())


def build_types_file(records):
    """The types/ file, now an EMPTY managed region.

    The emitter switched from custom key types (MAC_KEY_*) to STANDARD system
    types (EIGHT_LEVEL etc.), which the 'complete' component already provides.
    Desktop environments like KDE load the standard types automatically but do
    NOT reliably load a layout's own custom types, which left every key stuck on
    level 1. So we no longer define any types here. The file is still written (as
    an empty managed region) and tracked for snapshot/rollback/uninstall so those
    paths need no special-casing; a stale custom-types file from an older install
    is overwritten to empty.
    """

    _ = records  # no custom types are emitted any more
    return '\n'.join([_BEGIN, '', _END, ''])


def build_symbols_files(records):
    """Return {base_layout: symbols_file_text}, one entry per distinct base.

    Each base's file (written to symbols/<base>x, e.g. symbols/plx) holds the
    xkb_symbols sections for every variant of every record that resolves to that
    base. The section name is the variant name (mac-k2x-ansi/iso), which the
    system rules wildcard resolves as <base>x(<variant>).

    The FIRST section in each file is flagged 'default': the registered layout
    is selectable WITHOUT a variant (the desktop picker always offers the bare
    layout row), and a file with no default section is only tolerated by
    libxkbcommon (first-section fallback, with a warning) -- the X server's own
    compiler is stricter. The default flag makes the bare '<base>x' selection
    well-defined everywhere instead of resolver-dependent.
    """

    by_base = {}
    for record in records:
        base = record.get('base_layout') or 'us'
        by_base.setdefault(base, []).append(record)

    files = {}
    for base in sorted(by_base):
        lines = [_BEGIN, '']
        first_section = True
        for record in sorted(by_base[base], key=lambda r: r['identifier']):
            for variant_name, block_text in record['variants']:
                _types, symbols_section = _split_variant_block(block_text)
                flags = ('default partial alphanumeric_keys' if first_section
                         else 'partial alphanumeric_keys')
                first_section = False
                lines.append('// %s : %s' % (record['identifier'], variant_name))
                lines.append(flags)
                lines.append(symbols_section)
                lines.append('')
        lines.append(_END)
        lines.append('')
        files[base] = '\n'.join(lines)
    return files


def build_rules_file(records):
    """Rules overlay for the <base>x model.

    Our variant sections live in symbols/<base>x, named after the layout, so the
    SYSTEM wildcard rule ('* layout variant = pc+%l%(v)') already resolves
    <base>x(mac-k2x-ansi) to symbols/<base>x section mac-k2x-ansi. The keys now
    reference STANDARD types from the system 'complete' component, so NO custom
    types mapping is needed either -- the whole keymap resolves through the system
    rules. All we must do is include the system ruleset so our registry's layout
    is recognised.

    Structure carried over from the session-breaking bug: the include is
    '%S/evdev' not '%S/rules/evdev' (the doubled path returns no components and
    breaks ALL keymaps).
    """

    _ = records  # symbols + standard types both resolve via the system wildcard
    ns = _NAMESPACE
    lines = ['// %s rules overlay' % ns, '']
    lines.append('! include %S/evdev')
    lines.append('')
    return '\n'.join(lines)


def _tagged_description(text):
    """Append the [kl2xkb] origin tag so custom layouts are distinguishable from
    system layouts in the desktop keyboard picker. The tag is short, unique to
    this tool, and makes the layout's origin unmistakable at a glance."""

    return '%s [kl2xkb]' % text


def build_registry_xml(records):
    """Register each '<base>x' layout with our variants in its variantList.

    libxkbregistry MERGES this file with the system registry. The layout name is
    the namespaced '<base>x' (see k2x_base_name) -- a NEW layout, distinct from
    the system base, so its symbols resolve from our symbols/<base>x file. (An
    earlier design registered variants UNDER the existing base, but KDE then
    derived the symbols file from the base's group and looked for our sections
    inside e.g. 'symbols/pl', which fails.)

    The layout-level configItem carries a description: the desktop picker always
    shows the layout itself as a selectable row (resolving to the file's
    'default' section -- see build_symbols_files), and without a description
    that row displays the raw identifier ('plx'). Records are grouped by
    base_layout (several exotic layouts may share the 'us' fallback).
    """

    # Group records by their base layout, registered as '<base>x'.
    by_base = {}
    for record in records:
        base = record.get('base_layout') or 'us'
        by_base.setdefault(base, []).append(record)

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">',
           '<xkbConfigRegistry version="1.1">', '  <layoutList>']
    for base in sorted(by_base):
        layout_name = k2x_base_name(base)
        layout_desc = _tagged_description('Macintosh layouts (%s)' % base)
        out += ['    <layout>', '      <configItem>',
                '        <name>%s</name>' % _xml_escape(layout_name),
                '        <shortDescription>%s</shortDescription>'
                % _xml_escape(base),
                '        <description>%s</description>'
                % _xml_escape(layout_desc),
                '      </configItem>', '      <variantList>']
        for record in sorted(by_base[base], key=lambda r: r['identifier']):
            for variant_name, _text in record['variants']:
                suffix = 'ANSI' if variant_name.endswith('ansi') else (
                    'ISO' if variant_name.endswith('iso') else variant_name)
                desc = _tagged_description(
                    '%s, %s)' % (record['display_name'], suffix))
                item = ['        <variant>', '          <configItem>',
                        '            <name>%s</name>' % _xml_escape(variant_name)]
                short_desc = record.get('short_desc')
                if short_desc:
                    item.append(
                        '            <shortDescription>%s</shortDescription>'
                        % _xml_escape(short_desc))
                item.append('            <description>%s</description>'
                            % _xml_escape(desc))
                iso_countries = record.get('iso_countries') or []
                if iso_countries:
                    item.append('            <countryList>')
                    for country in iso_countries:
                        item.append('              <iso3166Id>%s</iso3166Id>'
                                    % _xml_escape(country))
                    item.append('            </countryList>')
                # NOTE: languageList is intentionally NOT emitted. When present,
                # KDE MERGES our <base>-k2x entry into the system layout group for
                # that language (e.g. Polish) and then derives the base symbols
                # file from the group -- looking for our variant section inside
                # 'symbols/pl' (which fails: "No Symbols named mac-k2x-ansi in
                # include file pl") and, worse, leaving the layout unselectable.
                # Without languageList, KDE treats <base>-k2x as its own group and
                # resolves the section from 'symbols/<base>-k2x' where it actually
                # lives. The flag is kept via countryList above.
                item += ['          </configItem>', '        </variant>']
                out += item
        out += ['      </variantList>', '    </layout>']
    out += ['  </layoutList>', '</xkbConfigRegistry>', '']
    return '\n'.join(out)


def build_compose_file(records):
    parts = []
    for record in sorted(records, key=lambda r: r['identifier']):
        if record['compose_text'].strip():
            parts.append('# === %s ===' % record['identifier'])
            parts.append(record['compose_text'])
            parts.append('')
    return '\n'.join(parts)


def _load_manifest(paths):
    text = _read(paths.manifest_file)
    if not text:
        return {'installed': {}}
    try:
        data = json.loads(text)
        data.setdefault('installed', {})
        return data
    except ValueError:
        return {'installed': {}}


def _rebuild_managed_files(paths, manifest, force, write_symbols=True):
    """Write the four kl2xkb-managed files from the manifest's current record set
    (or remove a file when nothing remains needs it).

    Every managed file lives in a kl2xkb-namespaced path and is regenerated in
    full from the manifest, so this same routine serves install AND uninstall:
    add or drop entries in the manifest, then call this to bring the files into
    line. It never touches system or user files (only our namespaced paths), so a
    rebuild can never disturb other layouts -- kl2xkb or otherwise.
    """

    merged = list(manifest['installed'].values())
    status = {}

    # All per-base symbols files that currently exist on disk (so we can remove
    # any that a new install no longer needs). They are the '<base>-k2x' files in
    # symbols/, identified by the managed-region marker inside them. We match on
    # the _BEGIN marker (content), NOT a filename suffix: the base tag is a single
    # 'x' now, too generic to filter filenames by, and the marker is authoritative.
    def _existing_k2x_symbols():
        found = []
        if os.path.isdir(paths.symbols_dir):
            for name in os.listdir(paths.symbols_dir):
                full = os.path.join(paths.symbols_dir, name)
                if not os.path.isfile(full):
                    continue
                text = _read(full)
                if text and _BEGIN in text:
                    found.append(full)
        return found

    if not merged:
        # Nothing installed: remove every managed file (clean slate).
        stale = [paths.types_file, paths.rules_file, paths.registry_file,
                 paths.compose_file] + _existing_k2x_symbols()
        for path in stale:
            if os.path.exists(path):
                os.remove(path)
                status[os.path.basename(path)] = 'removed'
        status['manifest'] = _write_if_changed(
            paths.manifest_file,
            json.dumps(manifest, indent=2, ensure_ascii=False), force)
        return status, merged

    # Write one symbols file per base layout; track which we wrote so we can
    # remove any leftover '<base>-k2x' file from a previous install.
    #
    # SYSTEM-MODE NOTE: with write_symbols=False (symbols living in the
    # system location instead), the desired set is empty, so the leftover
    # loop below removes EVERY marked user-side symbols file -- which is
    # exactly the migration a user-mode -> system-mode switch needs, since a
    # user-dir copy would shadow the system one in the compositor's search.
    symbols_by_base = build_symbols_files(merged) if write_symbols else {}
    written_symbol_paths = set()
    for base, content in symbols_by_base.items():
        path = paths.symbols_file_for(base)
        written_symbol_paths.add(path)
        status['symbols:%s' % k2x_base_name(base)] = _write_if_changed(
            path, content, force)
    for path in _existing_k2x_symbols():
        if path not in written_symbol_paths:
            os.remove(path)
            status['symbols:%s' % os.path.basename(path)] = 'removed'

    status['types'] = _write_if_changed(
        paths.types_file, build_types_file(merged), force)
    status['rules'] = _write_if_changed(
        paths.rules_file, build_rules_file(merged), force)
    status['registry'] = _write_if_changed(
        paths.registry_file, build_registry_xml(merged), force)
    compose = build_compose_file(merged)
    if compose.strip():
        status['compose'] = _write_if_changed(paths.compose_file, compose, force)
    elif os.path.exists(paths.compose_file):
        # No layout needs compose any more; drop the stale file.
        os.remove(paths.compose_file)
        status['compose'] = 'removed'
    status['manifest'] = _write_if_changed(
        paths.manifest_file,
        json.dumps(manifest, indent=2, ensure_ascii=False), force)
    return status, merged


def _call_with_fd2_captured(call):
    """Run call() with OS-level stderr redirected into a capture buffer.

    libxkbcommon logs compile diagnostics with fprintf straight to file
    descriptor 2 -- invisible to Python-level redirection, and eaten by the
    TUI's alternate screen before anyone can read it. Duplicating fd 2 onto
    a temp file for the duration captures every byte the C side emits.
    Returns (result, captured_text). tempfile is a lazy import to keep the
    generated installer's import surface unchanged (precedent: ctypes in
    validate_keymap).
    """

    import tempfile

    sys.stderr.flush()
    saved_fd = os.dup(2)
    capture = tempfile.TemporaryFile()
    os.dup2(capture.fileno(), 2)
    try:
        result = call()
    finally:
        sys.stderr.flush()
        os.dup2(saved_fd, 2)
        os.close(saved_fd)
    capture.seek(0)
    captured = capture.read().decode('utf-8', errors='replace')
    capture.close()
    return result, captured


def validate_keymap(identifier, variant_name, paths=None):
    """Compile one installed layout the way a Wayland compositor does, returning
    (ok, error_text).

    This is the validation that matters: it resolves the rules file, pulls in the
    types and symbols components, chains the system rules, and assembles the FULL
    keymap via libxkbcommon's RMLVO path (xkb_keymap_new_from_names) against the
    real XKB tree -- exactly what the compositor does at session start. An
    isolated xkb_symbols compile (wrapping the block in a synthetic keymap that
    supplies its own types) does NOT exercise this and cannot catch rules/types
    structural bugs, which is how a session-breaking install slipped through once.

    Returns (ok, message, diagnostics): (True, '', diagnostics) on success,
    (False, message, diagnostics) on a compile failure -- diagnostics being
    whatever the C side printed to fd 2 during the compile (possibly empty,
    and possibly non-empty even on success: libxkbcommon reports recoverable
    problems like unknown keysyms as [ERROR] lines while still assembling a
    keymap). If libxkbcommon is unavailable it returns (True, 'unavailable',
    ''); on a real Linux target it is always present (it is the compositor's
    own library).
    """

    import ctypes
    import ctypes.util

    libname = ctypes.util.find_library('xkbcommon')
    if not libname:
        return True, 'unavailable', ''
    try:
        xkb = ctypes.CDLL(libname)
        xkb.xkb_context_new.restype = ctypes.c_void_p
        xkb.xkb_context_new.argtypes = [ctypes.c_int]
        xkb.xkb_keymap_new_from_names.restype = ctypes.c_void_p

        class _Names(ctypes.Structure):
            _fields_ = [('rules', ctypes.c_char_p), ('model', ctypes.c_char_p),
                        ('layout', ctypes.c_char_p), ('variant', ctypes.c_char_p),
                        ('options', ctypes.c_char_p)]

        xkb.xkb_keymap_new_from_names.argtypes = [
            ctypes.c_void_p, ctypes.POINTER(_Names), ctypes.c_int]
        xkb.xkb_keymap_unref.argtypes = [ctypes.c_void_p]

        def _compile():
            context = xkb.xkb_context_new(0)
            names = _Names(b'evdev', b'pc105', identifier.encode(),
                           variant_name.encode(), None)
            return xkb.xkb_keymap_new_from_names(
                context, ctypes.byref(names), 0)

        keymap, diagnostics = _call_with_fd2_captured(_compile)
        if keymap:
            xkb.xkb_keymap_unref(keymap)
            return True, '', diagnostics
        return False, ('libxkbcommon could not assemble keymap for %s(%s)'
                       % (identifier, variant_name)), diagnostics
    except Exception as error:
        # never block on a probe bug
        return True, 'validation error: %s' % error, ''


def validate_installed(records, paths=None):
    """Validate every variant of every record against the on-disk tree.

    Returns (ok, failures, diagnostics): failures is a list of (identifier,
    variant, message); diagnostics is a list of (identifier, variant, text)
    for every compile whose C-side output was non-empty, success or not.
    Call AFTER the files are written (the keymap is assembled from them) and
    BEFORE reporting success.
    """

    paths = paths or InstallPaths()
    failures = []
    diagnostics = []
    for record in records:
        base = k2x_base_name(record.get('base_layout') or 'us')
        for variant_name, _text in record['variants']:
            # Compile the way it is actually selected: <base>-k2x(mac-k2x-variant).
            ok, message, noise = validate_keymap(base, variant_name, paths)
            if noise.strip():
                diagnostics.append(
                    (record['identifier'], variant_name, noise.strip()))
            if not ok:
                failures.append((record['identifier'], variant_name, message))
    return (not failures), failures, diagnostics


def _snapshot_files(paths):
    """Capture current contents of every managed file (or None if absent), so a
    failed install can be rolled back to the exact prior state.

    Includes every per-base '<base>-k2x' symbols file currently on disk, so
    rollback restores or removes them exactly.
    """

    files = [paths.types_file, paths.rules_file, paths.registry_file,
             paths.compose_file, paths.manifest_file]
    if os.path.isdir(paths.symbols_dir):
        for name in os.listdir(paths.symbols_dir):
            full = os.path.join(paths.symbols_dir, name)
            if not os.path.isfile(full):
                continue
            text = _read(full)
            if text and _BEGIN in text:
                files.append(full)
    return {path: _read(path) for path in files}


def _restore_files(snapshot):
    """Restore managed files from a snapshot: rewrite saved contents, and remove
    any file that did not exist before (its snapshot value is None)."""

    for path, content in snapshot.items():
        if content is None:
            if os.path.exists(path):
                os.remove(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8') as handle:
                handle.write(content)


def install_records(new_records, paths=None, force=False, validate=True,
                    write_symbols=True):
    """Install records, then validate the assembled keymap and ROLL BACK on
    failure so a broken layout never reaches the live XKB tree.

    Sequence: snapshot the current managed files -> write the new tree -> compile
    every affected layout via libxkbcommon RMLVO (validate_installed) -> if any
    fail, restore the snapshot exactly (prior state byte-for-byte) and report the
    failure instead of success. With validate=False the check is skipped (used by
    callers that validate separately); when libxkbcommon is unavailable the check
    passes (it cannot run), which only happens off a real Linux target.
    """

    paths = paths or InstallPaths()
    snapshot = _snapshot_files(paths)

    manifest = _load_manifest(paths)
    added, refreshed = [], []
    for record in new_records:
        ident = record['identifier']
        (refreshed if ident in manifest['installed'] else added).append(ident)
        manifest['installed'][ident] = record

    status, merged = _rebuild_managed_files(paths, manifest, force,
                           write_symbols=write_symbols)

    result = {'paths': paths, 'status': status, 'added': added,
              'refreshed': refreshed,
              'all_unchanged': all(v == 'unchanged' for v in status.values()),
              'installed_count': len(merged), 'validated': False,
              'rolled_back': False, 'failures': [], 'diagnostics': []}

    if validate:
        ok, failures, diagnostics = validate_installed(new_records, paths)
        result['validated'] = ok
        result['failures'] = failures
        result['diagnostics'] = diagnostics
        if not ok:
            # The assembled keymap did not compile -- undo everything.
            _restore_files(snapshot)
            result['rolled_back'] = True
            result['added'] = []
            result['refreshed'] = []
    return result


def list_installed(paths=None):
    """Return the list of currently-installed records (from the manifest).

    Manifest-driven and read-only: reports what is installed on THIS system,
    regardless of which installer or tool put it there.
    """

    paths = paths or InstallPaths()
    manifest = _load_manifest(paths)
    return list(manifest['installed'].values())


def uninstall_one(identifier, paths=None, force=False):
    """Remove one layout, rebuilding the managed files from what remains.

    Safe by construction: the remaining layouts are regenerated intact from the
    manifest, and only kl2xkb-namespaced files are touched. Returns a result dict
    with 'removed' (the identifier or None if it was not installed) and the
    rebuild status.
    """

    paths = paths or InstallPaths()
    manifest = _load_manifest(paths)
    if identifier not in manifest['installed']:
        return {'paths': paths, 'removed': None,
                'reason': 'not installed', 'installed_count':
                len(manifest['installed'])}
    del manifest['installed'][identifier]
    status, merged = _rebuild_managed_files(paths, manifest, force)
    return {'paths': paths, 'removed': identifier, 'status': status,
            'installed_count': len(merged)}


def uninstall_all(paths=None):
    """Remove every kl2xkb-managed file and the manifest (full clean slate).

    Touches only kl2xkb-namespaced paths; the system rules/registry and the
    user's own files are never modified. Returns a result dict listing what was
    removed.
    """

    paths = paths or InstallPaths()
    removed = []
    targets = [paths.types_file, paths.rules_file, paths.registry_file,
               paths.compose_file, paths.manifest_file]
    # Every per-base symbols file we manage, matched by our managed-region marker.
    if os.path.isdir(paths.symbols_dir):
        for name in os.listdir(paths.symbols_dir):
            full = os.path.join(paths.symbols_dir, name)
            if not os.path.isfile(full):
                continue
            text = _read(full)
            if text and _BEGIN in text:
                targets.append(full)
    for path in targets:
        if os.path.exists(path):
            try:
                os.remove(path)
                removed.append(os.path.basename(path))
            except OSError:
                pass
    return {'paths': paths, 'removed': removed}


# --- system-location install (symbols only) --------------------------------
#
# System mode moves ONLY the per-base symbols files to the system XKB tree:
# that placement is what the X server's own compiler (and therefore the KDE
# keyboard preview and pure Xorg sessions) can see. Rules/registry overlays
# stay user-side in both modes (libxkbregistry reads XDG paths -- that is
# what makes desktop pickers work), and XCompose is per-user by nature.
# These functions are policy-free engine pieces: root checks, escalation, and
# UI live in the generated installer.

SYSTEM_SYMBOLS_DIR = '/usr/share/X11/xkb/symbols'
SYSTEM_MANIFEST_DIR = '/var/lib/kl2xkb'
SYSTEM_MANIFEST_FILE = os.path.join(SYSTEM_MANIFEST_DIR, 'manifest.json')


def system_symbols_writable():
    """True when the system symbols dir sits on a writable filesystem.

    Detects immutable/read-only-/usr distros BEFORE any escalation attempt:
    ST_RDONLY is a mount property, visible without privileges. A False here
    means system mode should be declined with a pointer to user mode (write
    PERMISSION is root's concern; a read-only MOUNT defeats root too).
    """

    directory = SYSTEM_SYMBOLS_DIR
    while directory and not os.path.isdir(directory):
        directory = os.path.dirname(directory)
    if not directory:
        return False
    try:
        flags = os.statvfs(directory).f_flag
    except OSError:
        return False
    return not (flags & os.ST_RDONLY)


def _load_system_manifest():
    text = _read(SYSTEM_MANIFEST_FILE)
    if not text:
        return {'files': {}}
    try:
        manifest = json.loads(text)
    except ValueError:
        return {'files': {}}
    if not isinstance(manifest, dict) or 'files' not in manifest:
        return {'files': {}}
    return manifest


def stage_system_symbols(records, directory):
    """Write the per-base symbols files into 'directory' for a system apply.

    Returns the list of staged file names ('plx', 'usx', ...). The staged
    content is byte-identical to what user mode would write; only the final
    destination differs.
    """

    os.makedirs(directory, exist_ok=True)
    names = []
    for base, content in build_symbols_files(records).items():
        name = k2x_base_name(base)
        with open(os.path.join(directory, name), 'w', encoding='utf-8') as fh:
            fh.write(content)
        names.append(name)
    return sorted(names)


def system_apply(staged_dir):
    """Apply staged symbols files to the system location (run as root).

    Safety rules, in order: every staged file must carry the managed-region
    marker (refuse to stage arbitrary content into the system tree); an
    existing TARGET that lacks the marker and is not in the system manifest is
    NEVER overwritten (refuse loudly -- it is somebody else's file); writes go
    through a temp file in the target directory plus os.replace (atomic on the
    same filesystem); and a failure mid-batch restores every file already
    replaced in this run (byte-for-byte) before returning.

    Returns {'written': [...], 'refused': [...], 'error': str | None}.
    """

    result = {'written': [], 'refused': [], 'error': None}
    manifest = _load_system_manifest()

    staged = []
    for name in sorted(os.listdir(staged_dir)):
        full = os.path.join(staged_dir, name)
        if not os.path.isfile(full):
            continue
        content = _read(full)
        if not content or _BEGIN not in content:
            result['refused'].append('%s (staged file lacks the managed '
                                     'marker)' % name)
            continue
        staged.append((name, content))

    backups = []                    # (target_path, previous_content | None)
    try:
        for name, content in staged:
            target = os.path.join(SYSTEM_SYMBOLS_DIR, name)
            existing = _read(target)
            if (existing is not None and _BEGIN not in existing
                    and name not in manifest['files']):
                result['refused'].append('%s (existing system file is not '
                                         'kl2xkb-managed)' % name)
                continue
            backups.append((target, existing))
            temp_path = target + '.kl2xkb-new'
            with open(temp_path, 'w', encoding='utf-8') as fh:
                fh.write(content)
            os.chmod(temp_path, 0o644)
            os.replace(temp_path, target)
            manifest['files'][name] = {'bytes': len(content)}
            result['written'].append(name)

        os.makedirs(SYSTEM_MANIFEST_DIR, exist_ok=True)
        with open(SYSTEM_MANIFEST_FILE, 'w', encoding='utf-8') as fh:
            fh.write(json.dumps(manifest, indent=2, ensure_ascii=False))
    except Exception as error:
        for target, previous in backups:
            try:
                if previous is None:
                    if os.path.exists(target):
                        os.remove(target)
                else:
                    with open(target, 'w', encoding='utf-8') as fh:
                        fh.write(previous)
            except OSError:
                pass
        result['error'] = str(error)
    return result


def system_remove():
    """Remove every manifest-listed system symbols file (run as root).

    A target is only removed while it still carries the managed marker; a
    file someone replaced by hand is left alone and reported. Returns
    {'removed': [...], 'skipped': [...]}.
    """

    result = {'removed': [], 'skipped': []}
    manifest = _load_system_manifest()
    for name in sorted(manifest['files']):
        target = os.path.join(SYSTEM_SYMBOLS_DIR, name)
        existing = _read(target)
        if existing is None:
            result['skipped'].append('%s (already gone)' % name)
        elif _BEGIN not in existing:
            result['skipped'].append('%s (no longer kl2xkb-managed; left '
                                     'in place)' % name)
        else:
            os.remove(target)
            result['removed'].append(name)
    if os.path.isdir(SYSTEM_MANIFEST_DIR):
        try:
            os.remove(SYSTEM_MANIFEST_FILE)
            os.rmdir(SYSTEM_MANIFEST_DIR)
        except OSError:
            pass
    return result


# Matches our per-record section names inside a symbols file; group(1) is
# the record identifier. Kept as a module-global _rgx per project convention.
_SECTION_ID_RGX = re.compile(r'xkb_symbols "mac-k2x-([a-z0-9]+)-(?:ansi|iso)"')


def system_installed_identifiers():
    """Map each present system symbols file to the layout identifiers whose
    sections it contains, parsed from the section names themselves (possible
    since names carry the record identifier). Returns {file_name: sorted ids}.
    """

    occupancy = {}
    for name, present in system_installed():
        if not present:
            continue
        content = _read(os.path.join(SYSTEM_SYMBOLS_DIR, name))
        if not content:
            continue
        ids = sorted(set(_SECTION_ID_RGX.findall(content)))
        if ids:
            occupancy[name] = ids
    return occupancy


def system_remove_files(names):
    """Remove SPECIFIC manifest-listed system files (run as root).

    The scoped sibling of system_remove, for when a base file's last layout
    is uninstalled. Same safety rules: only manifest-listed names, only
    files carrying the managed-region marker. Returns
    {'removed': [...], 'skipped': [...]}.
    """

    manifest = _load_system_manifest()
    result = {'removed': [], 'skipped': []}
    for name in names:
        if name not in manifest['files']:
            result['skipped'].append('%s (not in system manifest)' % name)
            continue
        full = os.path.join(SYSTEM_SYMBOLS_DIR, name)
        content = _read(full)
        if content is None:
            del manifest['files'][name]
            result['skipped'].append('%s (already absent)' % name)
            continue
        if _BEGIN not in content:
            result['skipped'].append('%s (no marker; left alone)' % name)
            continue
        try:
            os.remove(full)
            del manifest['files'][name]
            result['removed'].append(name)
        except OSError as error:
            result['skipped'].append('%s (%s)' % (name, error))
    if manifest['files']:
        os.makedirs(SYSTEM_MANIFEST_DIR, exist_ok=True)
        with open(SYSTEM_MANIFEST_FILE, 'w', encoding='utf-8') as handle:
            json.dump(manifest, handle, indent=2, ensure_ascii=False)
    else:
        # last managed file gone: clear the manifest like system_remove does
        try:
            os.remove(SYSTEM_MANIFEST_FILE)
            os.rmdir(SYSTEM_MANIFEST_DIR)
        except OSError:
            pass
    return result


def system_installed():
    """Return [(name, still_present)] for manifest-listed system files."""

    manifest = _load_system_manifest()
    return [
        (name, os.path.isfile(os.path.join(SYSTEM_SYMBOLS_DIR, name)))
        for name in sorted(manifest['files'])
    ]


def dump_records(records, directory):
    """Write the raw XKB/Compose files to a folder for manual inspection/use."""
    os.makedirs(directory, exist_ok=True)
    written = []
    for record in records:
        for variant_name, symbols_text in record['variants']:
            path = os.path.join(directory, '%s-%s' % (record['identifier'], variant_name))
            with open(path, 'w', encoding='utf-8') as handle:
                handle.write(symbols_text)
            written.append(path)
        if record['compose_text'].strip():
            path = os.path.join(directory, 'Compose.%s' % record['identifier'])
            with open(path, 'w', encoding='utf-8') as handle:
                handle.write(record['compose_text'])
            written.append(path)
    return written


def _by_identifier(ident):
    for record in RECORDS:
        if record['identifier'] == ident:
            return record
    return None


def _by_language(language):
    return [r for r in RECORDS if r['language'].lower() == language.lower()]


def _print_list():
    groups = {}
    for record in RECORDS:
        groups.setdefault(record['language'], []).append(record)
    for language in sorted(groups):
        print('%s:' % language)
        for record in sorted(groups[language], key=lambda r: r['display_name']):
            variants = ', '.join(v[0] for v in record['variants'])
            flag = '' if record['compose_complete'] else '  [compose partial]'
            print('  %-14s %s)  [%s]%s'
                  % (record['identifier'], record['display_name'], variants, flag))


def _print_preview(ident):
    record = _by_identifier(ident)
    if record is None:
        print('no such layout: %s' % ident)
        return 1
    print('%s)' % record['display_name'])
    print('  identifier:   %s' % record['identifier'])
    print('  language:     %s' % record['language'])
    print('  source:       %s' % (record['source_id'] or '(unknown)'))
    print('  variants:     %s' % ', '.join(v[0] for v in record['variants']))
    print('  keys:         %d' % record['key_count'])
    print('  dead keys:    %d' % record['dead_key_count'])
    print('  compose:      %d bytes, %s'
          % (len(record['compose_text']),
             'complete' if record['compose_complete'] else 'PARTIAL'))
    return 0


def _report_lines(report, full=False):
    """The install report as a list of lines (shared by print, pager, log).

    full=False (the screen) summarizes compile diagnostics in one line;
    full=True (the log file) includes every captured diagnostic body, so
    libxkbcommon's fd-2 output finally survives the alternate screen.
    """

    lines = []
    if report.get('rolled_back'):
        lines.append('INSTALL FAILED -- rolled back; nothing was changed.')
        lines.append('')
        lines.append('The assembled keymap did not compile, so the install '
                     'was undone')
        lines.append('to protect your session. Affected layout(s):')
        for identifier, variant, message in report.get('failures', []):
            lines.append('  %s (%s): %s' % (identifier, variant, message))
        lines.append('')
        lines.append('Your existing keyboard configuration is untouched.')
        lines.extend(_diagnostics_lines(report, full))
        return lines
    if report['all_unchanged']:
        lines.append('Already up to date (nothing changed); no need to '
                     'log out.')
        return lines
    if report['added']:
        lines.append('Installed: %s' % ', '.join(report['added']))
    if report['refreshed']:
        lines.append('Refreshed: %s' % ', '.join(report['refreshed']))
    lines.append('Files written under %s' % report['paths'].root)
    lines.extend(_diagnostics_lines(report, full))
    return lines


def _diagnostics_lines(report, full):
    """Captured libxkbcommon compile diagnostics, summarized or in full."""

    diagnostics = report.get('diagnostics') or []
    if not diagnostics:
        return []
    lines = ['']
    if not full:
        lines.append('%d compile(s) produced libxkbcommon diagnostics; '
                     'full text is in the log file.' % len(diagnostics))
        return lines
    lines.append('libxkbcommon compile diagnostics (%d):'
                 % len(diagnostics))
    for identifier, variant, text in diagnostics:
        lines.append('')
        lines.append('--- %s (%s) ---' % (identifier, variant))
        for row in text.splitlines():
            lines.append('  ' + row)
    return lines


def _write_report_log(lines):
    """Persist the report so it survives the alternate screen. Returns the
    log path, or None when writing was not possible (never fatal)."""

    state_dir = os.path.join(
        os.environ.get('XDG_STATE_HOME')
        or os.path.expanduser('~/.local/state'), 'kl2xkb')
    try:
        os.makedirs(state_dir, exist_ok=True)
        stamp = __import__('time').strftime('%Y%m%d_%H%M%S')
        path = os.path.join(state_dir, 'install_report_%s.log' % stamp)
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write('\n'.join(lines) + '\n')
        return path
    except OSError:
        return None


def _report(report, pager=False):
    lines = _report_lines(report)
    log_path = _write_report_log(_report_lines(report, full=True))
    if log_path is not None:
        lines.append('')
        lines.append('Full report saved: %s' % log_path)
    if pager and len(lines) > 20:
        _page('\n'.join(lines))
        return
    for line in lines:
        print(line)
    print('')
    print('Some Linux desktop environments might require a log out to allow')
    print('picking the new layout(s).')


def _require_linux():
    """Refuse a mutating verb anywhere but Linux.

    Installation writes XKB layouts into the system tree
    (/usr/share/X11/xkb) or the per-user tree (~/.config/xkb) -- Linux
    mechanisms with no equivalent elsewhere. Called by the verbs that WRITE
    (and by the interactive menu); the inspection verbs (--list, --preview,
    --dump, --help) work on any platform.
    """

    if not sys.platform.startswith('linux'):
        sys.stderr.write(
            'Installation runs on Linux only (system tree or ~/.config/xkb).\n')
        if sys.platform == 'darwin':
            sys.stderr.write(
                'On macOS these layouts already exist natively. You can still '
                'inspect this bundle here:\n'
                '  --list, --preview ID, --dump DIR, --help\n')
        sys.exit(2)


_SYSTEM_VERBS = ('--system-apply', '--system-remove')


def _refuse_root():
    """Refuse to run as root, except for the two narrow system verbs.

    Everything except --system-apply/--system-remove targets your personal
    ~/.config/xkb: running THAT as root would write root-owned files into the
    wrong home and install nothing for your normal user. The system verbs are
    the ONLY root-legitimate operations (they copy pre-staged, marker-verified
    symbols files into /usr/share/X11/xkb/symbols); the interactive menu and
    --install-all-system invoke them through sudo/doas/run0/sudo-rs for you,
    so there is still no reason to launch this installer with sudo yourself.
    Catches plain root, sudo, and a setuid-root binary alike (all give euid 0).
    """

    if hasattr(os, 'geteuid') and os.geteuid() == 0:
        sys.stderr.write(
            'Refusing to run as root. This installer runs as your normal '
            'user and escalates by itself\n'
            'for the system-location step (the menu and '
            '--install-all-system handle it).\n')
        sudo_user = os.environ.get('SUDO_USER')
        if sudo_user:
            sys.stderr.write(
                'It looks like you used sudo -- run it directly as %s '
                '(no sudo).\n' % sudo_user)
        sys.exit(2)


def _require_root(verb):
    """The system verbs write to /usr and MUST run as root."""

    if not hasattr(os, 'geteuid') or os.geteuid() != 0:
        sys.stderr.write(
            '%s writes to the system XKB tree and must run as root.\n'
            'Use the interactive menu or --install-all-system, which '
            'escalate for you.\n' % verb)
        sys.exit(2)


def main(argv):
    force = '--force' in argv
    argv = [a for a in argv if a != '--force']
    cmd = argv[0] if argv else ''

    # The two root-only verbs dispatch BEFORE the root refusal; everything
    # else keeps the absolute refusal.
    if cmd == '--system-apply' and len(argv) > 1:
        _require_linux()
        _require_root(cmd)
        result = system_apply(argv[1])
        for name in result['written']:
            print('system: wrote symbols/%s' % name)
        for line in result['refused']:
            print('system: REFUSED %s' % line)
        if result['error']:
            print('system: FAILED and rolled back: %s' % result['error'])
            return 1
        return 0 if not result['refused'] else 1
    if cmd == '--system-remove-files' and len(argv) > 1:
        _require_linux()
        _require_root(cmd)
        result = system_remove_files(argv[1:])
        for name in result['removed']:
            print('system: removed symbols/%s' % name)
        for line in result['skipped']:
            print('system: skipped %s' % line)
        return 0
    if cmd == '--system-remove':
        _require_linux()
        _require_root(cmd)
        result = system_remove()
        for name in result['removed']:
            print('system: removed symbols/%s' % name)
        for line in result['skipped']:
            print('system: skipped %s' % line)
        return 0

    if not argv:
        _require_linux()
        _refuse_root()
        return _menu(force=force)

    if cmd == '--list':
        _print_list(); return 0
    if cmd == '--preview' and len(argv) > 1:
        return _print_preview(argv[1])
    if cmd == '--install' and len(argv) > 1:
        _require_linux()
        _refuse_root()
        record = _by_identifier(argv[1])
        if record is None:
            print('no such layout: %s' % argv[1]); return 1
        _report(install_records([record], force=force)); return 0
    if cmd == '--install-lang' and len(argv) > 1:
        _require_linux()
        _refuse_root()
        records = _by_language(argv[1])
        if not records:
            print('no layouts in language group: %s' % argv[1]); return 1
        _report(install_records(records, force=force)); return 0
    if cmd == '--install-all':
        _require_linux()
        _refuse_root()
        _report(install_records(list(RECORDS), force=force)); return 0
    if cmd == '--install-all-system':
        _require_linux()
        _refuse_root()
        return _system_install_records(list(RECORDS), force=force)
    if cmd == '--dump' and len(argv) > 1:
        _refuse_root()
        written = dump_records(list(RECORDS), argv[1])
        print('Wrote %d files to %s' % (len(written), argv[1])); return 0
    if cmd == '--list-installed':
        _require_linux()
        _refuse_root()
        installed = list_installed()
        if not installed:
            print('No kl2xkb layouts are installed.'); return 0
        print('Installed layouts (%d):' % len(installed))
        for record in sorted(installed, key=lambda r: r['identifier']):
            print('  %-18s %s)' % (record['identifier'], record['display_name']))
        return 0
    if cmd == '--uninstall' and len(argv) > 1:
        _require_linux()
        _refuse_root()
        result = uninstall_one(argv[1], force=force)
        if result['removed'] is None:
            in_system = any(
                argv[1] in ids
                for ids in system_installed_identifiers().values())
            if not in_system:
                print('not installed: %s' % argv[1]); return 1
            print('%s is not user-installed, but has system copies.'
                  % argv[1])
        else:
            print('Removed %s (%d remain). Some desktops might need a '
                  'log out.'
                  % (result['removed'], result['installed_count']))
        _system_sync_after_uninstall([argv[1]])
        return 0
    if cmd == '--uninstall-all':
        _require_linux()
        _refuse_root()
        result = uninstall_all()
        if result['removed']:
            print('Removed: %s' % ', '.join(result['removed']))
            print('Some Linux desktops might need a log out.')
        else:
            print('Nothing user-installed; nothing to remove there.')
        if system_installed():
            answer = _ask(
                'Also remove the system-location files? [Y/n] ')
            if answer.strip().lower() not in ('n', 'no'):
                _escalate_run(['--system-remove'])
        return 0

    print(__doc__)
    return 0


def _enter_screen():
    """Switch to the terminal's alternate screen buffer (like less/vim), so the
    menu has its own screen and the user's prompt and scrollback are restored
    untouched on exit. No-op when stdout is not a terminal (piped/redirected)."""

    if sys.stdout.isatty():
        sys.stdout.write('\033[?1049h\033[H')
        sys.stdout.flush()


def _leave_screen():
    """Restore the normal screen buffer (prompt and history come back)."""

    if sys.stdout.isatty():
        sys.stdout.write('\033[?1049l')
        sys.stdout.flush()


def _clear():
    """Clear the alternate screen and home the cursor."""

    if sys.stdout.isatty():
        sys.stdout.write('\033[H\033[2J')
        sys.stdout.flush()


def _drain_input():
    """Discard pending terminal input before prompting.

    Mouse-wheel scrolling in the alternate screen makes many terminals emit
    arrow-key escape sequences; without a drain those land verbatim in the
    next input() and corrupt the answer. termios is a lazy import: the TUI
    only runs on Linux, but this module's inspection verbs must import
    everywhere.
    """

    if not sys.stdin.isatty():
        return
    try:
        import termios
        termios.tcflush(sys.stdin.fileno(), termios.TCIFLUSH)
    except (ImportError, OSError):
        pass


def _pause(message='Press Enter to continue...'):
    """Wait for the user before leaving a screen (so output is readable)."""

    _drain_input()
    try:
        input('\n' + message)
    except (EOFError, KeyboardInterrupt):
        pass


def _page(text):
    """Show long text through the system pager (less/$PAGER), via the stdlib
    pydoc pager, which falls back to plain printing when no pager exists.

    The pager (less) runs its OWN alternate-screen switch and, on quit, restores
    the NORMAL screen -- which drops us out of the TUI's alternate buffer. Without
    re-entering, the menu would then draw on the real screen and leave remnants
    mixed with the prompt on exit. So re-assert our alternate screen right after
    the pager returns, putting us back in the buffer the TUI's exit will restore.
    """

    pydoc.pager(text)
    _enter_screen()


def _ask(prompt):
    """Prompt for a line of input. Returns '' on EOF/Ctrl-C so callers treat it
    as 'go back' rather than crashing."""

    _drain_input()
    try:
        return input('\n' + prompt).strip()
    except (EOFError, KeyboardInterrupt):
        return ''


def _grouped_records():
    """RECORDS grouped by language, languages sorted, records sorted by name."""

    groups = {}
    for record in RECORDS:
        groups.setdefault(record['language'], []).append(record)
    for language in groups:
        groups[language].sort(key=lambda r: r['display_name'])
    return groups


def _list_text():
    """The full embedded-layout listing as a string (for paging)."""

    lines = ['Layouts in this installer:', '']
    for language in sorted(_grouped_records()):
        lines.append('%s:' % language)
        for record in _grouped_records()[language]:
            variants = ', '.join(v[0] for v in record['variants'])
            flag = '' if record['compose_complete'] else '  [compose partial]'
            lines.append('  %-16s %s)  [%s]%s'
                         % (record['identifier'], record['display_name'],
                            variants, flag))
        lines.append('')
    return '\n'.join(lines)


def _preview_text(ident):
    """A layout's structured summary as a string (for paging)."""

    record = _by_identifier(ident)
    if record is None:
        return 'No such layout: %s' % ident
    lines = [
        '%s)' % record['display_name'],
        '  identifier:   %s' % record['identifier'],
        '  language:     %s' % record['language'],
        '  source:       %s' % (record['source_id'] or '(unknown)'),
        '  variants:     %s' % ', '.join(v[0] for v in record['variants']),
        '  keys:         %d' % record['key_count'],
        '  dead keys:    %d' % record['dead_key_count'],
        '  compose:      %d bytes, %s' % (
            len(record['compose_text']),
            'complete' if record['compose_complete'] else 'PARTIAL'),
    ]
    return '\n'.join(lines)


def _numbered_records():
    """A flat, numbered list of all records (language-grouped order) for
    selection. Returns a list so index N-1 maps to choice N."""

    ordered = []
    for language in sorted(_grouped_records()):
        ordered.extend(_grouped_records()[language])
    return ordered


def _select_records():
    """Selection screen: show a numbered list, accept a number, a comma-list of
    numbers, 'all', or a language name. Returns the chosen records, or [] to go
    back. Loops on invalid input rather than failing."""

    ordered = _numbered_records()
    while True:
        _clear()
        print('Select layouts to install')
        print('=' * 40)
        current_language = None
        for index, record in enumerate(ordered, start=1):
            if record['language'] != current_language:
                current_language = record['language']
                print('\n%s:' % current_language)
            variants = ', '.join(v[0] for v in record['variants'])
            print('  %2d) %-16s %s)  [%s]'
                  % (index, record['identifier'], record['display_name'],
                     variants))
        print('')
        print('Enter a number, a comma-list (e.g. 1,3,4), a language name,')
        print("'all' for everything, or blank to go back.")
        answer = _ask('> ')

        if not answer:
            return []
        if answer.lower() == 'all':
            return list(ordered)

        # A language name?
        by_lang = [r for r in ordered if r['language'].lower() == answer.lower()]
        if by_lang:
            return by_lang

        # A number or comma-list of numbers.
        chosen = []
        ok = True
        for token in answer.replace(' ', '').split(','):
            if not token.isdigit() or not (1 <= int(token) <= len(ordered)):
                ok = False
                break
            chosen.append(ordered[int(token) - 1])
        if ok and chosen:
            # de-duplicate while preserving order
            seen = set()
            unique = []
            for record in chosen:
                if record['identifier'] not in seen:
                    seen.add(record['identifier'])
                    unique.append(record)
            return unique

        _clear()
        print('Did not understand %r. Try a number, comma-list, language, or '
              "'all'." % answer)
        _pause()


def _system_sync_after_uninstall(removed_ids, ask=True):
    """Mirror an uninstall into the system tree (ask-first, default yes).

    Finds every system base file whose parsed occupancy includes a removed
    identifier, rebuilds it from the remaining occupants' records (staged,
    then applied through the existing escalated verb), and removes base
    files whose last occupant left (scoped root verb). No system copies of
    the removed layouts means no questions and no escalation.
    """

    import shutil
    import tempfile

    occupancy = system_installed_identifiers()
    removed = set(removed_ids)
    rebuilds = {}
    removals = []
    for name, ids in occupancy.items():
        if not removed.intersection(ids):
            continue
        remaining = [i for i in ids if i not in removed]
        if remaining:
            rebuilds[name] = remaining
        else:
            removals.append(name)
    if not rebuilds and not removals:
        return

    if ask:
        answer = _ask('Also remove from the system location? [Y/n] ')
        if answer.strip().lower() in ('n', 'no'):
            print('System copies left in place.')
            return

    if rebuilds:
        keep_ids = set()
        for ids in rebuilds.values():
            keep_ids.update(ids)
        keep_records = [r for r in RECORDS if r['identifier'] in keep_ids]
        staged_dir = tempfile.mkdtemp(prefix='kl2xkb-sync-')
        try:
            # build_symbols_files keys by BASE ('us'); the system tree
            # holds the namespaced file names ('usx'), so stage under those.
            for name, content in build_symbols_files(keep_records).items():
                with open(os.path.join(staged_dir, k2x_base_name(name)),
                          'w', encoding='utf-8') as handle:
                    handle.write(content)
            code = _escalate_run(['--system-apply', staged_dir])
            if code not in (0,):
                print('System rebuild did not complete (code %r).' % code)
        finally:
            shutil.rmtree(staged_dir, ignore_errors=True)
    if removals:
        code = _escalate_run(['--system-remove-files'] + sorted(removals))
        if code not in (0,):
            print('System file removal did not complete (code %r).' % code)


def _escalate_run(extra_args):
    """Run this installer with 'extra_args' through the first available
    privilege-escalation tool (Toshy convention: sudo, doas, run0, sudo-rs).

    Runs interactively so the tool can prompt for a password on the user's
    terminal. Returns the child's exit code, or None when no escalation tool
    exists -- in which case the exact command is printed for manual use, so
    the user is never stuck.
    """

    script = os.path.abspath(__file__)
    command_tail = [sys.executable, script] + list(extra_args)
    for tool in ('sudo', 'doas', 'run0', 'sudo-rs'):
        if shutil.which(tool):
            print('Escalating with %s for the system-location step...' % tool)
            print('', flush=True)
            return subprocess.call([tool] + command_tail)
    print('No escalation tool found (looked for sudo, doas, run0, sudo-rs).')
    print('Run this yourself as root, then re-run the installer:')
    print('  ' + ' '.join(command_tail))
    return None


def _system_install_records(records, force=False):
    """The system-mode install: validate as the user, escalate for symbols,
    then finish the user-side files.

    Sequence: (1) decline early on read-only /usr (immutable distros);
    (2) build and VALIDATE the complete tree in a throwaway user-style root,
    so nothing broken is ever staged; (3) stage the symbols files and
    escalate for --system-apply; (4) on success, write the user-side pieces
    (rules/registry/compose) WITHOUT symbols -- which also removes any stale
    user-dir symbols files, since a user copy would shadow the system one --
    and validate the final assembly, which now resolves against the system
    files.
    """

    if not system_symbols_writable():
        print('The system XKB location is on a read-only filesystem')
        print('(immutable distro?). System mode is not possible here;')
        print('use the user-location install instead (keyboard preview')
        print('will not work there).')
        return 1

    check_root = tempfile.mkdtemp(prefix='kl2xkb-precheck-')
    try:
        report = install_records(records, paths=InstallPaths(root=check_root),
                                 force=True)
        if report.get('validation') == 'failed':
            print('Pre-validation FAILED; nothing was installed anywhere:')
            _report(report, pager=True)
            return 1
    finally:
        shutil.rmtree(check_root, ignore_errors=True)

    staged = tempfile.mkdtemp(prefix='kl2xkb-stage-')
    keep_staged = False
    try:
        names = stage_system_symbols(records, staged)
        print('Staged %d symbols file(s): %s' % (len(names), ', '.join(names)))
        code = _escalate_run(['--system-apply', staged])
        if code is None:
            # The printed manual command references the staged dir: keep it,
            # or the instructions would point at a deleted path.
            keep_staged = True
            print('(The staged files are kept at %s until you do.)' % staged)
            return 1
        if code != 0:
            print('System apply did not complete (exit %d); the user-side'
                  % code)
            print('files were left untouched.')
            return code

        report = install_records(records, force=force, write_symbols=False)
        _report(report, pager=True)
        print('')
        print('Symbols are in the system location: the keyboard preview and')
        print('Xorg sessions can use these layouts. Uninstalling later needs')
        print('the same escalation (the Manage menu handles it).')
        return 0
    finally:
        if not keep_staged:
            shutil.rmtree(staged, ignore_errors=True)


def _confirm_and_install(records, force=False):
    """Show the selection, ask the destination, confirm, then install.

    System mode (symbols in /usr/share/X11/xkb/symbols) is the primary path:
    it is the only placement the X server's own compiler sees, which is what
    makes the KDE keyboard preview and pure Xorg sessions work. User mode
    stays available for machines without escalation or with read-only /usr.
    """

    if not records:
        return
    _clear()
    print('About to install %d layout(s):' % len(records))
    print('')
    for record in records:
        variants = ', '.join(v[0] for v in record['variants'])
        print('  %s)  [%s]' % (record['display_name'], variants))
    print('')
    print('Where should the layouts be installed?')
    print('  1) System location (recommended -- keyboard preview works;')
    print('     needs admin rights for one step) [default]')
    print('  2) User location only (no admin rights, but the keyboard')
    print('     preview will NOT work)')
    print('  blank) Cancel')
    answer = _ask('\nChoice [1]: ').strip().lower()
    if answer in ('', '1', 'system', 's'):
        _clear()
        _system_install_records(records, force=force)
        _pause()
        return
    if answer not in ('2', 'user', 'u'):
        _clear()
        print('Cancelled. Nothing was installed.')
        _pause()
        return
    _clear()
    print('Installing to the user location (keyboard preview will not work).')
    report = install_records(records, force=force)
    _report(report, pager=True)
    _pause()


def _install_flow(force=False):
    """The Install branch: pick layouts, confirm, install."""

    records = _select_records()
    if records:
        _confirm_and_install(records, force=force)


def _preview_flow():
    """The Preview branch: pick one layout by number, page its summary."""

    ordered = _numbered_records()
    _clear()
    print('Preview a layout')
    print('=' * 40)
    for index, record in enumerate(ordered, start=1):
        print('  %2d) %-16s %s)'
              % (index, record['identifier'], record['display_name']))
    answer = _ask('\nNumber to preview (blank to go back): ')
    if not answer:
        return
    if answer.isdigit() and 1 <= int(answer) <= len(ordered):
        _page(_preview_text(ordered[int(answer) - 1]['identifier']))
    else:
        _clear()
        print('Not a valid number.')
        _pause()


def _dump_flow():
    """The Dump branch: write raw XKB/Compose files to a chosen directory."""

    _clear()
    print('Dump raw XKB/Compose files')
    print('=' * 40)
    print('This writes the symbols, variants, and Compose files to a directory')
    print('for inspection (it does NOT install them).')
    directory = _ask('\nTarget directory (blank to go back): ')
    if not directory:
        return
    _clear()
    try:
        dump_records(RECORDS, directory)
        print('Wrote raw files to %s' % directory)
    except OSError as error:
        print('Could not write to %s: %s' % (directory, error))
    _pause()


def _menu(force=False):
    """The guided, dependency-free interactive menu.

    Runs on bare `python3 install_*.py` with no options. Uses the terminal's
    alternate screen so each stage has its own screen and the user's prompt and
    scrollback return untouched on exit (including Ctrl-C). Every stage accepts a
    blank line / Ctrl-C to go back, and 'q' quits from the top level.
    """

    _enter_screen()
    try:
        while True:
            _clear()
            print('keylayout_to_xkb installer')
            print('  generator %s · build %s'
                  % (_GENERATOR_VERSION, _GENERATOR_BUILD))
            print('  generated %s' % _GENERATED_AT)
            print('=' * 40)
            print('%d layout(s) available in this installer.\n' % len(RECORDS))
            print('  1) Install layouts onto this system')
            print('  2) List layouts in this installer')
            print('  3) Preview a layout in this installer')
            print('  4) Manage layouts already installed on this system')
            print('  5) Dump raw XKB files (no install)')
            print('  q) Quit')
            answer = _ask('\nChoice: ').lower()

            if answer in ('q', 'quit', 'exit', ''):
                break
            if answer == '1':
                _install_flow(force=force)
            elif answer == '2':
                _page(_list_text())
            elif answer == '3':
                _preview_flow()
            elif answer == '4':
                _manage_flow(force=force)
            elif answer == '5':
                _dump_flow()
            else:
                _clear()
                print('Unknown choice: %r' % answer)
                _pause()
    finally:
        _leave_screen()
    return 0


def _manage_flow(force=False):
    """List everything installed anywhere with location markers, and offer
    to uninstall one layout or all of them -- user and system trees linked:
    removing a layout removes its sections regardless of location (asking
    once before the escalated system step)."""

    installed = list_installed()
    user_ids = set(record['identifier'] for record in installed)
    occupancy = system_installed_identifiers()
    sys_ids = set()
    for ids in occupancy.values():
        sys_ids.update(ids)
    display_names = dict(
        (record['identifier'], record['display_name']) for record in RECORDS)
    for record in installed:
        display_names[record['identifier']] = record['display_name']

    _clear()
    print('Manage installed layouts')
    print('=' * 40)
    all_ids = sorted(user_ids | sys_ids)
    if not all_ids:
        print('Nothing is installed.')
        _pause()
        return
    listing = []
    for index, identifier in enumerate(all_ids, start=1):
        if identifier in user_ids and identifier in sys_ids:
            marker = '(user+sys)'
        elif identifier in user_ids:
            marker = '(user)'
        else:
            marker = '(sys)'
        listing.append('  %3d) %-20s %-10s %s)'
                       % (index, identifier, marker,
                          display_names.get(identifier, identifier)))
    if len(listing) > 20:
        _page('\n'.join(listing))
        print('(the full list is in the pager above; scroll with it)')
    else:
        for line in listing:
            print(line)
    print('')
    print('Enter a number to uninstall that layout (from BOTH locations,')
    print('asked before the system step), "all" to remove everything, or')
    print('blank to go back.')
    answer = _ask('> ').strip().lower()

    if not answer:
        return
    if answer == 'all':
        confirm = _ask('Remove ALL %d installed layout(s)? [y/N] '
                       % len(all_ids))
        if confirm.lower() in ('y', 'yes'):
            result = uninstall_all()
            _clear()
            if result['removed']:
                print('Removed: %s' % ', '.join(result['removed']))
            if system_installed():
                sys_answer = _ask(
                    'Also remove the system-location files? [Y/n] ')
                if sys_answer.strip().lower() not in ('n', 'no'):
                    code = _escalate_run(['--system-remove'])
                    if code == 0:
                        print('System-location files removed.')
                    else:
                        print('System removal did not complete.')
            print('\nSome Linux desktops might need a log out to update '
                  'the picker.')
        else:
            _clear()
            print('Cancelled.')
        _pause()
        return
    if answer.isdigit() and 1 <= int(answer) <= len(all_ids):
        identifier = all_ids[int(answer) - 1]
        confirm = _ask('Uninstall %s? [y/N] ' % identifier)
        if confirm.lower() in ('y', 'yes'):
            _clear()
            if identifier in user_ids:
                result = uninstall_one(identifier, force=force)
                print('Removed %s (%d remain in the user tree).'
                      % (result['removed'], result['installed_count']))
            _system_sync_after_uninstall([identifier])
            print('\nSome Linux desktops might need a log out to update '
                  'the picker.')
        else:
            _clear()
            print('Cancelled.')
        _pause()
        return
    _clear()
    print('Not a valid choice.')
    _pause()


# ---- generator stamp ----
_GENERATOR_VERSION = 'rc20260704c/gen20260704d/br20260704/up20260704/uckt20260703d'
_GENERATOR_BUILD = 'c974a1f4'
_GENERATED_AT = '2026-07-05 01:15:07'


# ---- embedded layout records (compressed payload) ----
_RECORDS_B64 = (
    'eNrtXVdzW0eWfvevQNEPlnclFW4GnKoQPd6RQ63smd21vByQuCQhggANgAp2eUvO2XLOOYxzGidJ'
    'tsdVNglR4U/Iv2SB2/ec86HRDYllPGzVwg++rdtfd58+fUL36XPB2y/L3H1ZJjPXqMetXmOpEXfm'
    'rsrMLTVarUZ3JT7Si1v1uD63ewipN7rrzdrR+VZtLR6CqgqU2ZOppLjMrhtri41Wr91dUU2atdby'
    'Rm0Z4aqi297oLMbzjfqwZrG9tre2vt6M967GRwcjtDd6e1N0ZYSCQ7VOo9bqdQeNbh/8W/0vM7dW'
    'W9yz6h7Zo1G9p9bqNpKGA8yR1YX57tG1hXazmzkwscWBuczdB1oHWsNmw6nefn2nvbHu3JG5dtBw'
    '4px3Zwo37b/hygNzV1P7wXwy1xSKWee6YZ+Z9L/e0fXRXis3XP+nW+f3Vf5S2XdgbrcAU4IBe3vm'
    'tmw2KuwePgL1qEaDh5v1fXyp12XuUL3ec/UoYe50CcupwQePelyrzy/EzfbhAa877dawwvMcrp8M'
    's5HrTZXc0Evo8L2UjsW43mg2awkNbsR1doiNTH+6XA0Vu8JkLb188q9CUV6O19kIC6bLP1cxx1WD'
    'K5ErFuXleJ2NsHC6hFXU4JVkcCenHiV5OV5nIyyaLmFlNXhZjZpXD3g5XmcjLDdVwlzFHK+oRi2o'
    'h2KVpc5GWH66hCkaPDWqq8S9qJTTUmchzMlOlzC1XEFVscNTD2WELXVmwkpT9g6hMrK+k5osMKxZ'
    'n6usCBuRU/YUyq4G6lEeMqoy4Bu+TB6Dl9m0zkbYlH1CyiL1qGYVfVl8mT7KVGcjbLpeIFTi7ScP'
    'J+8qrjjwcqzORtiUvUDqKSM1aqB8oycvx+tshE3ZC6hthk/bjPZyuxWvKhKkyoqwETllj6A8o1/A'
    'vVCv0azHaiuU5eqJKBux0/USYerbiykZQkHW4xobwEbidP1FmHr5kpI4T/EnkJfjdRbCpuwvqkpH'
    'y+pRVZJXzuFLelCdjbDp+ouKMmcl9agoGkohvqQH1ZkJK0/7mJOeFhzl3pVzKGbl5XidjbApOy9l'
    '1YLUqvnKYITycrzORtiUnVcq5+pRUaeBUh5fpo8S1dkIm/IRJvXsLh2jarzhKHGNDWAjcbpuLErP'
    'z6njV1vLcgVfpo8y1dkIm64bi9RSBXmy/Z34UGpTQ66xAWwkTteJRUqogkAJfU4NnpeX43U2wqbs'
    'sFLZz6vBE930nKK8HK+zETZlN1VVgycPR+14nVQJ/NE6N31YCJuym4pS+5pNham20D4U19s9tWwR'
    'V07A2AidsttKDVmARHQarWVFRYFrJ4FspE7RXyTj1hu1uBN3G10yb43O4sbaUjM+oghJtYKs36XC'
    'zeRXpuyH06idqx6FNMak/mWpsxE2XT/sKX1Jvb+fxWgK1rmOelijKZUp+2FP7YbTQ1AhfShZtNTZ'
    'CJuuH/b8hA8F5XRd5c8KilVYx5CCVcam633THbqbeolQbZvSpTTX2Qibrvf1lI9Nd3cFZQCL6l+W'
    'Ohth0/W5XhoDU84iSrdRaajOXGcjbLo+11PHl/SIHShnG6mHpc5G2HR9bhodd9N9iRKuKJUxc52F'
    'sCn73PSQ75XJ/Lc3FppxbXGjl27jUuZdFGYjd7r+wE3JUdJVVKa/qP5lqbMRNm0/mzIjKS93arQN'
    'dtSD9yuTUUZii3/ev2+6XEx1tCAOamBD0og71PG/Cubzxr791986VcLIjmXF1PEJe7TOjdI6I2H7'
    'bylVpsuxdFT1KJgeep2RsFv3ladLmJda3eRKyU0iyINH6u7NdUgYLuZf9l3Er958U+USCbupvT95'
    'm7kDgLXFXqPd0oGF5O2uK43sKhVu2T+Zplv/evMl0nTD/gFycDptBvP72ouru/UXI7QeWmvXu4Nm'
    'SX21MVDTifOQyuF/w95uHLTfNegkSWvoXsv9XLn70rG7M7WlpXixd+1GqzmAXSktNV5R2/m12nrS'
    'Y+Zu4p0scqO12NyoxwOeNYcDeLs6tWZvvnu40VtcufLA3IHWPVfPDfMV7th9CekNjW57Z9kNgwZ/'
    'JLlhsFaz3IZZbsMst2GW2zDLbZjlNsxyG2a5DbPchlluwyy3YZbbMMttmOU2zHIbZrkNs9yGWW7D'
    'LLdhltswy22Y5TbMchtmuQ2z3IZZbsMst2GW2/B/JbfhD97U/z/MbfiD2SCz3IZZboOe23BZmt8w'
    '/N2H9XY3nu/FR3rD34G4PPMfJfUqs9TuZMbTEQ60Ls/sT3454qrMJfxoRAKPm0t7FtutXq3RiutX'
    'ZertuJtptXtMbm8lzqy0u73MgAW1ZpxJKdg7bHx93Io7tV5czywczfAw8732/JHVhb0D4eoNOdho'
    'NhLMYKYrmUJC0rBx4EUZNcPGcD0z3fjOjbi1GHeHDLscLHQms6sXd9YarVpvMOsr/nbFYCGukerr'
    'Mtck2n/dgd5VA+b+bcDK3uWZ2/51sFvMGoC+kwJ/OybIkhEZEPIRQOZMyDwhnwBkyYSspMjTJxjp'
    'VI19VqnPZ6XPsmtABkznK4DMm5Ahjf6ajF4umpBRirxwitnkVHImNgU0+Qs//kOgVROlIfP+baG0'
    'Yuo05Dl9BEgTn0Lm/WeANPE+ZN6fBN6b+BQy7/8hfRpnFDGdJwFp6jNi3r8OvDfRGQnv7wXeOyao'
    '8P4b4L0HKpRseDQV+vVb0aGkXtOhX7+VyRR9A1KU6F4QeMeE9FLk5kMy7WxoQjIrH4U+8yYkMej0'
    't7CQRjpZOJ6EPssmZCFF/tt5mJJfGD4G20NTiyLx/sRXwnsva4KWiAkgeZ5xamXu9J/QacUEJXHe'
    'ul869T0TksX5OTAQJmRAEnDh5PMyfGBibeDS8M/L8GYkicDWq4AsmJAsAq8CoUYka9NLoE2RCSna'
    'dB9ok2uCsrS8AcObpCUgadmCBY1MCyom7x0wTyZ5CllTHgZNMU1JjOPH0KdxdNaU70BTAhOS5/45'
    '9Gmae0hzP4iaEk7QlFA05WsQaiOUNeUUaIpJAkLRlF+g06oJypryAGiKSVTF8H8D5tykKZFoygug'
    'KSbWRqwpL4D8G5GsKeCfg6IJySJwCgg18Un8zsugKTkTUjTlftAU4+xZWn6G4U3SErGmwIJGJkJL'
    'NKXTgDROqcRT+gmQJQOynCPkPwFpsqYVHv1HQJpYX+HRfwakae5VHv0XQFbROae3J5p/PvcK+OcU'
    'ornoc7LXc2WvNwpmL739dwG7oQXssj6Bncy6FjQbq8fAWBUsYJ+7fgy6tqFpJTZflK4dG9Uhd/2m'
    'dO1ULGiS8E3Zfzpu1gLOcdfvSteujSGkEZtfgeGydc226yTsrn0busLoBwDtW9Bkwra/gEW3MAT8'
    '/YtgxSzMZpd/4eTLgM5Z0B6j3xZ0aJlkwDJy8hNAW2QEnPpDYKpsdPNKngL5y9n65j31qacAbeMg'
    '2zewG1HRDObNwPaHsDaRBSwKCeY461nQrJCPg0La6BCFfBy6tqFZIWGv5dioFoV8CxSyakGzQr4D'
    'CulYwKKQ74FC2hjCCvk1KKSta1FIOHL5NrQo5IOADixoVsgvYdEtDIFtxUugYhZmR6KQrwDa4g4i'
    'Uch3QMUsk4xEIT8FtEVGYO/wMCiNjW5RSJC/nK1vUcjjgLZxkBUSNgdRCZwu37Drp+KPxOsyRj8Z'
    'QziikLOg5XT8AJw6fRuat3KPA7poQ4sS/B2UILTBeaN2HDqv2tC8/X0RDkC2vtlk33oeAmSBrw4C'
    'NubIGe91GKNkQ4tcge/L2XgJlv4JgFt7J+5sQTQuslEuR7n34YhkI0UOaZ8C2rasYNs+hGWNbHBe'
    '1i+hc9uyyqnme9it25ZVFP8UmKC8jRQ5ifwEnds4DnYCTGcusMFlPZ8EeNkGZ7b8ArTghjvJj9N3'
    '2y+L3if1+lb7Zdhq5wxI1vfN+8D3uiYku1IImji+Ccme8U1AVkxIER3YObkFE5R94mfgbksmJInM'
    '1lNwZDYNz/q8BX2Gpj5ZfzYhYCX7GUQym+DE7AQmJLPpLUBWTUhhE/gzt2iCMps+BzaVTUhm03Fg'
    'k2l4VpMt6DMsK9FUX2xkbrmtkFlv1hbjlXazHncSiU3u4Ya3PSixZ5+/IrOr1c50e7VWvdapK9n+'
    'lyG2e3QtEx9pdHvdpFWjNxTtpP90/LMieW7e58pRkZ8E4oNiX8I/ThKdRhDtNfoQzEq2AwgiS9OH'
    'Q2SyLUcQbSj7zwgorw9HYtB/DkCeBqJl7cPBMh9qIIpV9SFcks9pINoA9t8AUHkUxGervrgLp6Ax'
    'k49U/S8AVNFAzMyPAZTXQMxM0MNCSQORFPblYsMpuhqINKX/KCyLPhwz8xvoSeM4H46234etr8YC'
    'PueckbVzA60nPt70HwGatGXhY82Zl6AnTej4gNJ/FtZOYwGblTMSKHCToyuCiE9nILwSavLEtuTM'
    'xwDSmMkB0v4rQJMOIqE7I2vnRhrhfH7ofwBSEGggtgUwu4I2Oz5bnBWOuzrH+Uhx9n4AaWvHG4o+'
    'mL6Cpi1sH88+Dj0VNRBz/EVYYI3jvAnow+1QURM6PiVsfwCSGYg5dndgjn9/4MWd22Ni76AxUeCq'
    'MJeqHTXIE1EeG5GPgME5DURLdeY14F1RA7F9gNhmsayBWIMeBF0MNBBp0O/3snF3s35hFMU7pz74'
    'z+RkhyDWfbhCzGk84J1VHzYsuYoGYjcB2y/2b662nzr9PURt9eFYfkCF3KwGIrX+8+/H4GreLya8'
    'cPIammIQfbggzpc0EF9lgMvUuRowV98FeXA1EAvN3wGkTVP8BQRRio4G4kumH4BhkQYirdyW2bmO'
    'Njv2F33oqaj1xNvIMxACDzRmsr84AzuZQFtp3maeBjde1qRdXMF7YMA9DcQuEzaseU0l+OKsD1v6'
    'vCai7Ao24UjqabrM4aozEFIKNbWRWy+ICPqawrMr6L8HUqDNTlzBMbDNmrDL3RVcdkQaTWLlH4Oe'
    'NPHlG6uzTwBIExU+SPZhuKI+HAvdGyB02gKzKzj7LGx6XXEF3g5cwZ6dOwLi2x6xEG6Z60bdwAQM'
    'b6Y3n4aTUFYDsarCnrTiayAS5k2wDG6ogdjLQlA4H2kgus3dgqOC72ggOkP14QiXr46CeHe7BTSF'
    'Gk1iPuC2uxiMgni72T8GjkLjE+8kN+HQ4WiEy+U67LUq+nDMzA+BmRqfZJP4EehzTgMxMyHK4Lsa'
    'iJh55jvYJGo08YZsC2gKNZpEVR8FLcxrIOY4+MpiKLrj70B3du9cd2giu0EvSlw3qjsTMHzA2oZQ'
    'j5PTQDTY9qsAKoyC2Apug3NiT+9r/N+GrZhTFK4FO+Da3p1zjVZ2L3CkwnWjXJuA4c3bhVNwwcfn'
    'iGDsXhkiuFlfQ8mNFARusyUNFfCIJwRVzGkoifS8D5EefURJnYNLwVJBQ0nqCiQ3eq6GKjHqe0CF'
    'GkoumeCG3df7kssluNr09b6qTD3wq6TxCy5sX4X7IW2OcFELF92hRhdc0H4GKH1EXqEfgfcVjfec'
    'vXXhJGS5RZp8Qez/EQj+aqsN6affQgqkPmKB+3oWgtraHEORaLghKzgaSiQaYtjZQEOJREPoOlvW'
    'UCLRJ0Gi8xpKJPoDkGh9ROEE3KqVihpKJBpSRj1PQ4lE/wCoSEOJRMMVta/3JRINd4O+3pdINPCr'
    'pPELbjxfA4nW5gg3nXBTHGp0wQ3n54DSRxSJBt5XNN5HItGQjcbb32Ds9uNRkGhttSGp9zuQaH1E'
    'kejnQKIx9Rd+W0+/8ngSrjwEpV98SNKsK0mzY3iw8GCxJMd3vIGoBmRYZCv2BiT/fzr/NZyjc8lN'
    'o9zpj7cTWQfb4Pn2BiL2p6BBwd5AZBtslJ+zNgCTDAlLgX3uYHe/ACmd0EAEA3J48/ZJgz0D/ZTM'
    '0/EGsn5wIZ+t2hvINR6kGeXtEgJGClTAC+wNZOF+hAZFewNZOFBFP29tAJYHElsC+6TBvHwJCzeh'
    'gSwcpJTmA9Do5KdRdF1+WHQ5qde1+GHQ4siA5H3cadF3R/QdkZxk9ATc4JVMSD5AQThONByRfNcH'
    '2eFOwYTk8xacASuhCUnytv0mbLCNo5OtPQ0BSMmPQKR8IPDE+AcCRh6QEJ+GsKx8w4JIznqGsKtn'
    'XAEO6sC9mm9cVfKnp+EIW3YMSMnkhyuvwESnZPJD/qRk9CGSj5gQaAh9E5KDcHB1Jx8nIJITb+GW'
    'RHJfEcnhuB9gsZxiZF8syeODJYhMS8CbxNMg2iWTcElOHihW1tgnqwuIYdYkhnI1DiniTtGEZHWB'
    'U37FJCpsnrffAnUxjs7qAkGmskkAONh5GvJhq0YkqwncblZMyyofB0A2t2fkPKsJXBf6JpHmbedp'
    'uA6Uz+wAKWn8IH6BiU4JhUJWY2hSPYnEQAgpDExIVhO4uiibFEoS/sGglk0Gla/Tzj4LauLmXbua'
    'SHYdLMHw4MYuSv2Oou6jXhMfpQC6k4JIiHyQiFBJsoGPOLK+Eco6AgbNyRmhnOoB9++SLT0CZUn5'
    'BOS0YIJKTgxcs0euCSpJMXCZlg2MUJ4WCKCTN0J5Wl/CtKpGKE/rU5iWcQkkhwXu/KOxE0fyw4+a'
    'ABw4cKSWPf+VdupIkHqG5dvnv4Icy6za42dt7SQkdAJCHE7BiufD1QkIY0AOlIaXgMZJOEJEvg0v'
    'B/oTcEB1ila80AOHULdsw8tx9CTsjKNA/6hk+ENXuhK+qn1VMsToegixzXLBgpb81gchqTSwoYni'
    'yvnHYOMUKCNjHYPE8uaRVtXJrUTxQJ3Dig1NHvKvOEYQXWQMWrH/HGmVn9xKkkc/gIxNG89YimIc'
    'I7wIz1iV2yOtLsIz0WqwFWHVhpYQBnwDks/Z4JK7DRnqw9QWOdPwD5zp8voQHGwYpAnsf8MSVGxo'
    'Edj7QGBdK5z3bbB7kITmMThnwALXSwUrnFMW4Z7fKVnhfIEEO2nXt8I5BfYpIMbOGfLnm5As49l7'
    'p4DfjeeBk35ZSZidobQdu2mkWeVizThv+XlIFbcSJ6cTYGxgZawkor8GvRetcFq2LeBUZCeGU8vh'
    'ZiwKrXA5+z8NepK14cWcvAvmxMpJOYlASl82b4Uzaz6B3q0SLUm4kEfhlK1wlmjY9LqBFc4S/QUQ'
    'Y5VoPnhswiWwZ++dJHoNRTO8mETzAaM10uxiEi2Z+PALC1WrEMlBAhgbWBkrqfg/Qu9WiWZTvgWc'
    'iqycYlO+Bck5UWSFi0Q/AxLtyC1nuJMUu2Mndn7PSQehQWNJQeNcmlBPsZuEgpA13B85roaSzR84'
    'R0fvS2KVP0GssqShJEAJ95Oc6hWORYfhRyiirIaSTSPcT0bhKArCunCj4HgaSuYIHp2vuMOxeOzP'
    'MMeyhpI5wo0V5yiFY4FU+PmAyNFQMke4sRrKJ+80Gq3B1qQX100fgagDyjOy4xgBj59Rnhk7ozjO'
    'hKbyKbaYC1fshKkFzWf7IWgRTmrB2U6QXCXbPlML/jTxKWhRmdCCY4XbkCzlTJoHy9425Ow6k+Yh'
    'X8lCUrF8J2JqwWNArFsuMEwtmFeQbiwfwJpaMK+OQ4vqhBYcMNqGxHZn0jxYhrchgd1BETbe5v36'
    'pYit8SLvV/hKrFA1QSW6AllR2awRymEIiJiJCIxA+bBwAjJEXHO3HLKA8Ip8xWS8pdt3/r3z8Iml'
    'X0oU0fWUF/aNbfmLHQgM+yUTlGX930eHCdyLD8N70f0jLSc24XMYMCA0MkAi4ZBuWg6MUBZ0+GrA'
    'M64W70H/a4TmwgSaJXoFCX7yGzAjUBYbiPOLNoxARWwgDcM1d8tiA+Er+arLeEfYHF3P8BLERj70'
    'glC+XzZBWe07o8NElyA2vOHrjrSc2ITFBhgQGhkgkWH4AEo+7x2Bsth8A2JjXC3e6N01QvMksZEf'
    'cIEE9YpRKOXXViBBueLJLjLayXdzP+18E0myeFY+b3WLJa7UvpubAJI8V7g842y5SE+4h2BMoToK'
    'YmHsw/0CZylFmlz04QKmmMXAi/p7hrozOQFRF4XQvckJ+HW4nBHLEZTfHoYoRGTGyrYTjr5O1gxm'
    'DwmZsq6FCD6WgpTJ77eMYiXD6iMwOZaOOUcfzvZeaMbynRX8PojkJYxi+dYK7gLkZyVGsHJpC7oc'
    'mGmQwAh8eADRshEs30gB00Iz08BhfDjmMFzzanMk4jdoUrFgRTLgCCn77FEwSwZ8aOfmzViWDDAq'
    '8kMio1iRjI9BMiwds2TAGdmzzI4lA36owiuZsSwZ8AmUb15tuaeEzPzATIMEGCD3XnJaRrEsGcC0'
    '0Mw08AkfjvkEFze0psuic6+LCTJdEf0PdFkxACXcez9YH8+ElPRLOIoXSyYobzQgm0MMBCJpsX6D'
    'Q6JkXiCSw0EvADIwIGVzCKOHptEhtxamFJmmBKmzkE5dNfUq8cb3QG1NLIWMVjj5F8smKLMUbv5F'
    'sxDJLIX8v6qJpRJh+w6QJpbKxglGD02jQ3InTCkyTQlyNyGft5qX/UpuB/uVc8d2vl8hc3UOvtUq'
    'ZblSu+6bAIL0fkgL588Ic2MaBBmTxYKGErZAmmQpp6EkBRjyQkuVURSkmMMv4FRCDSUjQsirqqEg'
    '4RsShfn7t9yYSENyYbGooWREyCgs5TWUzBFyJ0vVURQkHcPPwVQiDSUjQsiriuZV/Z0I089oq4DX'
    'cfjJI4GOh7uOj4W7JPQx1lCCXSBeEkwYx7PrfgDwvh3PhxP4NB1+cGgMz6EbyHKR9JYxvAS5noYw'
    'jJ1+CXHBx6aOnX4JcN0L9Dh2PPf/IOADO575A59uyW3POJ75Awnfkqc2hpfA1jMwXzv9EtZ6AfDB'
    'mJiafqr63Bu6hJp+sPocfN9ZLlvxEvyB9LUga8WL14UzVGTHS5QAci4Dx4oXFwSfV0fpFcmNG81e'
    'Y8/iSq1TWxxwJHEQ7Y3e+sbA5O9C9xEfWa+1usM/iUA+gNiyf78ee8oOf1hjbuSvCwyfzbgXz12V'
    'Wao1u3FSmdA7GHFQu9Ea/vEBN0je4ysnm0/eNbrt+WattbxRW467g/e3D/+KwdxSIxkmM1dbosIq'
    'FdYPU6nTolK3xqUele5KCwvxGpc6XOJaruS6blpYpE4X4wUqLS9TaaVNpcYilfgVd3E0LdRrXDhE'
    'pZgKB7nUpYHqG9zgKPUaL2xQiRrExIGYQTR0TIyIudVhAi0RV5caTSpxHfFhaYNLNIvlGhe4VKcC'
    '9bRMNC13aaWWN4jdyzT7lRoXCLVCi75CA68wP1ZoEg1q16CBG8SMBq1Ng+bSIGY0iBkHF6ju4Bot'
    '20GiabW2wKWDXCIBWV2k/ld56VZjImd1eZ1KK3dSiSa0usrdNblAbFpd5954uqvdJS6tUIlYsEoM'
    'axK8SZQ1GzRQc5Wm3FyjKfOQTa7b4AKDNmi1m8SXNdabtSWidW2ZCytcoj7WGlwgJq+1GUaLskZU'
    'rLGwt2hGrToXCN4i1rV47BZNqEUjt4jSVpdfbXAPNKHWUS5QD20itE3rvb7IJRp5/U5+1SEa1mkW'
    'dxIvOzEtQofgbKk6bS7QCncOc4FsXLdGItRdILHqLnKBOuvGXFjhEk22SwR2uVeaRneNC9wVF4jA'
    'LpNALO1y1zTlLk25S5xlle/eRaP12Db1iJIejdbjqg4XqKseDdc7TKSwGTlUIwk7RDw4tEZDH9qg'
    '7g/XuEAwtoFHiGVH2sSpo2yb2eYe7dA07qK+7tqY4z+yM/ReiUfrNMB7VW8QRHel3enN1+PB8l3F'
    'fm1uoTbwneoP3qSvL8vcc9kd/wuhsegq'
)
RECORDS = json.loads(
    zlib.decompress(base64.b64decode(_RECORDS_B64)).decode('utf-8'))
# normalise variant tuples (JSON gives lists)
for _r in RECORDS:
    _r['variants'] = [tuple(v) for v in _r['variants']]


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))


# End of file #
