"""
keylayout_to_xkb/install/generate.py

Generate a SELF-CONTAINED installer file from one or more LayoutRecords.

The output is a single runnable Python file that embeds the records as a data
literal plus all the install logic inline, so it runs on a machine that does NOT
have keylayout_to_xkb installed -- copy the one file, run it. It writes the
layouts into the per-user XKB tree (~/.config/xkb), idempotently.

WHY EMBED THE LOGIC. The installer file cannot import keylayout_to_xkb (the
point is to need nothing else), so the install runtime is carried inline. To
avoid drift from the tested installer.py, the embedded runtime is a compact
dict-based mirror of the same contract (wholesale regeneration, hash-skip,
manifest), exercised by the same kinds of tests.

FILE STRUCTURE (as agreed): logic first (readable when opened), the big record
payloads last, and the single launcher line at the very bottom -- so a reader
sees what it does before the embedded data, and only the final line executes.
"""

import json

from keylayout_to_xkb.install.catalog import LayoutRecord


__version__ = '20260623'


def _record_to_dict(record: LayoutRecord) -> 'dict':
    """Serialise a record to the plain dict the embedded runtime consumes."""

    return {
        'identifier': record.identifier,
        'display_name': record.display_name,
        'language': record.language,
        'source_id': record.source_id,
        'variants': [list(v) for v in record.variants],   # JSON-friendly
        'compose_text': record.compose_text,
        'compose_complete': record.compose_complete,
        'dead_key_count': record.dead_key_count,
        'key_count': record.key_count,
    }


# The embedded runtime: the standalone installer's whole body EXCEPT the record
# data and the launcher. Kept as a plain string so the generator can write it
# verbatim. It mirrors installer.py's contract but operates on dicts and needs
# only the standard library. Logic lives here (top of the output file); the
# record literal and launcher are appended after it.
_RUNTIME = r'''#!/usr/bin/env python3
"""
Self-contained installer for Apple macOS keyboard layouts converted to XKB.

Generated by keylayout_to_xkb. Not affiliated with or endorsed by Apple.

Installs the embedded layout(s) into your per-user XKB tree (~/.config/xkb),
which is rootless and works on Wayland sessions (libxkbcommon >= 0.10.0, 2020+).
After installing, LOG OUT and back in so the compositor rebuilds its keymap and
the layout appears in your keyboard settings picker.

Usage:
  python3 THIS_FILE.py                 interactive menu
  python3 THIS_FILE.py --list          list embedded layouts
  python3 THIS_FILE.py --install ID    install one layout by identifier
  python3 THIS_FILE.py --install-lang L install all layouts in a language group
  python3 THIS_FILE.py --install-all   install every embedded layout
  python3 THIS_FILE.py --dump DIR      write the raw XKB/Compose files to DIR
  python3 THIS_FILE.py --force ...     rewrite even if unchanged
  python3 THIS_FILE.py --preview ID    print a layout's structured summary
"""

import os
import sys
import json
import hashlib

from xml.sax.saxutils import escape as _xml_escape


_NAMESPACE = 'keylayout_to_xkb'
_BEGIN = '// >>> keylayout_to_xkb managed region (do not edit by hand) >>>'
_END = '// <<< keylayout_to_xkb managed region <<<'


def user_xkb_root():
    base = os.environ.get('XDG_CONFIG_HOME') or os.path.join(
        os.path.expanduser('~'), '.config')
    return os.path.join(base, 'xkb')


class InstallPaths:
    def __init__(self, root=None):
        self.root = root or user_xkb_root()
        self.symbols_dir = os.path.join(self.root, 'symbols')
        self.rules_dir = os.path.join(self.root, 'rules')
        self.symbols_file = os.path.join(self.symbols_dir, _NAMESPACE)
        self.rules_file = os.path.join(self.rules_dir, 'evdev')
        self.registry_file = os.path.join(self.rules_dir, 'evdev.xml')
        self.compose_file = os.path.join(self.root, 'Compose.%s' % _NAMESPACE)
        self.manifest_file = os.path.join(self.root, '%s.manifest.json' % _NAMESPACE)


def _read(path):
    try:
        with open(path, 'r', encoding='utf-8') as handle:
            return handle.read()
    except FileNotFoundError:
        return None


def _write_if_changed(path, content, force):
    existing = _read(path)
    if existing is not None and existing == content and not force:
        return 'unchanged'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(content)
    return 'written'


def build_symbols_file(records):
    lines = [_BEGIN, '']
    for record in sorted(records, key=lambda r: r['identifier']):
        for variant_name, symbols_text in record['variants']:
            lines.append('// %s : %s' % (record['identifier'], variant_name))
            lines.append(symbols_text)
            lines.append('')
    lines.append(_END)
    lines.append('')
    return '\n'.join(lines)


def build_rules_file(records):
    lines = ['// %s rules overlay' % _NAMESPACE, '! include %S/rules/evdev', '']
    lines.append('! layout\tvariant\t=\tsymbols')
    for record in sorted(records, key=lambda r: r['identifier']):
        for variant_name, _text in record['variants']:
            lines.append('  %s\t%s\t=\t%s(%s)'
                         % (record['identifier'], variant_name, _NAMESPACE, variant_name))
    lines.append('')
    return '\n'.join(lines)


def build_registry_xml(records):
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!DOCTYPE xkbConfigRegistry SYSTEM "xkb.dtd">',
           '<xkbConfigRegistry version="1.1">', '  <layoutList>']
    for record in sorted(records, key=lambda r: r['identifier']):
        base_desc = record['display_name']
        if base_desc.count('(') > base_desc.count(')'):
            base_desc = base_desc + ')'
        out += ['    <layout>', '      <configItem>',
                '        <name>%s</name>' % _xml_escape(record['identifier']),
                '        <description>%s</description>' % _xml_escape(base_desc),
                '      </configItem>', '      <variantList>']
        for variant_name, _text in record['variants']:
            suffix = 'ANSI' if variant_name.endswith('ansi') else (
                'ISO' if variant_name.endswith('iso') else variant_name)
            out += ['        <variant>', '          <configItem>',
                    '            <name>%s</name>' % _xml_escape(variant_name),
                    '            <description>%s</description>'
                    % _xml_escape('%s, %s)' % (record['display_name'], suffix)),
                    '          </configItem>', '        </variant>']
        out += ['      </variantList>', '    </layout>']
    out += ['  </layoutList>', '</xkbConfigRegistry>', '']
    return '\n'.join(out)


def build_compose_file(records):
    parts = []
    for record in sorted(records, key=lambda r: r['identifier']):
        if record['compose_text'].strip():
            parts.append('# === %s ===' % record['identifier'])
            parts.append(record['compose_text'])
            parts.append('')
    return '\n'.join(parts)


def _load_manifest(paths):
    text = _read(paths.manifest_file)
    if not text:
        return {'installed': {}}
    try:
        data = json.loads(text)
        data.setdefault('installed', {})
        return data
    except ValueError:
        return {'installed': {}}


def install_records(new_records, paths=None, force=False):
    paths = paths or InstallPaths()
    manifest = _load_manifest(paths)
    added, refreshed = [], []
    for record in new_records:
        ident = record['identifier']
        (refreshed if ident in manifest['installed'] else added).append(ident)
        manifest['installed'][ident] = record
    merged = list(manifest['installed'].values())

    status = {}
    status['symbols'] = _write_if_changed(paths.symbols_file, build_symbols_file(merged), force)
    status['rules'] = _write_if_changed(paths.rules_file, build_rules_file(merged), force)
    status['registry'] = _write_if_changed(paths.registry_file, build_registry_xml(merged), force)
    compose = build_compose_file(merged)
    if compose.strip():
        status['compose'] = _write_if_changed(paths.compose_file, compose, force)
    status['manifest'] = _write_if_changed(
        paths.manifest_file, json.dumps(manifest, indent=2, ensure_ascii=False), force)

    return {'paths': paths, 'status': status, 'added': added, 'refreshed': refreshed,
            'all_unchanged': all(v == 'unchanged' for v in status.values()),
            'installed_count': len(merged)}


def dump_records(records, directory):
    """Write the raw XKB/Compose files to a folder for manual inspection/use."""
    os.makedirs(directory, exist_ok=True)
    written = []
    for record in records:
        for variant_name, symbols_text in record['variants']:
            path = os.path.join(directory, '%s-%s' % (record['identifier'], variant_name))
            with open(path, 'w', encoding='utf-8') as handle:
                handle.write(symbols_text)
            written.append(path)
        if record['compose_text'].strip():
            path = os.path.join(directory, 'Compose.%s' % record['identifier'])
            with open(path, 'w', encoding='utf-8') as handle:
                handle.write(record['compose_text'])
            written.append(path)
    return written


def _by_identifier(ident):
    for record in RECORDS:
        if record['identifier'] == ident:
            return record
    return None


def _by_language(language):
    return [r for r in RECORDS if r['language'].lower() == language.lower()]


def _print_list():
    groups = {}
    for record in RECORDS:
        groups.setdefault(record['language'], []).append(record)
    for language in sorted(groups):
        print('%s:' % language)
        for record in sorted(groups[language], key=lambda r: r['display_name']):
            variants = ', '.join(v[0] for v in record['variants'])
            flag = '' if record['compose_complete'] else '  [compose partial]'
            print('  %-14s %s)  [%s]%s'
                  % (record['identifier'], record['display_name'], variants, flag))


def _print_preview(ident):
    record = _by_identifier(ident)
    if record is None:
        print('no such layout: %s' % ident)
        return 1
    print('%s)' % record['display_name'])
    print('  identifier:   %s' % record['identifier'])
    print('  language:     %s' % record['language'])
    print('  source:       %s' % (record['source_id'] or '(unknown)'))
    print('  variants:     %s' % ', '.join(v[0] for v in record['variants']))
    print('  keys:         %d' % record['key_count'])
    print('  dead keys:    %d' % record['dead_key_count'])
    print('  compose:      %d bytes, %s'
          % (len(record['compose_text']),
             'complete' if record['compose_complete'] else 'PARTIAL'))
    return 0


def _report(report):
    if report['all_unchanged']:
        print('Already up to date (nothing changed).')
    else:
        if report['added']:
            print('Installed: %s' % ', '.join(report['added']))
        if report['refreshed']:
            print('Refreshed: %s' % ', '.join(report['refreshed']))
        print('Files written under %s' % report['paths'].root)
    print('')
    print('IMPORTANT: log out and back in for the layout to appear in your')
    print('keyboard settings picker (the compositor must rebuild its keymap).')


def main(argv):
    force = '--force' in argv
    argv = [a for a in argv if a != '--force']

    if not argv:
        return _menu()

    cmd = argv[0]
    if cmd == '--list':
        _print_list(); return 0
    if cmd == '--preview' and len(argv) > 1:
        return _print_preview(argv[1])
    if cmd == '--install' and len(argv) > 1:
        record = _by_identifier(argv[1])
        if record is None:
            print('no such layout: %s' % argv[1]); return 1
        _report(install_records([record], force=force)); return 0
    if cmd == '--install-lang' and len(argv) > 1:
        records = _by_language(argv[1])
        if not records:
            print('no layouts in language group: %s' % argv[1]); return 1
        _report(install_records(records, force=force)); return 0
    if cmd == '--install-all':
        _report(install_records(list(RECORDS), force=force)); return 0
    if cmd == '--dump' and len(argv) > 1:
        written = dump_records(list(RECORDS), argv[1])
        print('Wrote %d files to %s' % (len(written), argv[1])); return 0

    print(__doc__)
    return 0


def _menu():
    """Minimal interactive fallback (full TUI added by a later generator)."""
    _print_list()
    print('')
    print('Run with --install ID, --install-lang LANG, --install-all, or --dump DIR.')
    return 0
'''


# The launcher that must come LAST (the only line that executes at run time).
_LAUNCHER = '''

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))


# End of file #
'''


def generate_installer(records: 'list') -> str:
    """Return the full text of a self-contained installer file for the records.

    Layout of the produced file: runtime logic first, then the embedded RECORDS
    data literal, then the launcher line. The records are embedded as a JSON
    string parsed at startup, which keeps the big payload readable-as-data and
    avoids any quoting hazards from embedding as Python source.
    """

    payload = [_record_to_dict(record) for record in records]
    # Embed as a JSON literal assigned to RECORDS. json.dumps handles all the
    # escaping of the XKB/Compose text safely; the runtime parses it at startup.
    data_blob = json.dumps(payload, ensure_ascii=False, indent=1)

    parts = []
    parts.append(_RUNTIME)
    parts.append('\n\n# ---- embedded layout records (data payload) ----\n')
    parts.append('_RECORDS_JSON = r"""\n')
    parts.append(data_blob)
    parts.append('\n"""\n')
    parts.append('RECORDS = json.loads(_RECORDS_JSON)\n')
    parts.append('# normalise variant tuples (JSON gives lists)\n')
    parts.append("for _r in RECORDS:\n")
    parts.append("    _r['variants'] = [tuple(v) for v in _r['variants']]\n")
    parts.append(_LAUNCHER)
    return ''.join(parts)


# End of file #
